// Code generated by ent, DO NOT EDIT.

package product

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBarcode holds the string denoting the barcode field in the database.
	FieldBarcode = "barcode"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldBrand holds the string denoting the brand field in the database.
	FieldBrand = "brand"
	// FieldCalories holds the string denoting the calories field in the database.
	FieldCalories = "calories"
	// FieldProtein holds the string denoting the protein field in the database.
	FieldProtein = "protein"
	// FieldFat holds the string denoting the fat field in the database.
	FieldFat = "fat"
	// FieldSaturatedFat holds the string denoting the saturated_fat field in the database.
	FieldSaturatedFat = "saturated_fat"
	// FieldCarbohydrates holds the string denoting the carbohydrates field in the database.
	FieldCarbohydrates = "carbohydrates"
	// FieldFiber holds the string denoting the fiber field in the database.
	FieldFiber = "fiber"
	// FieldSugars holds the string denoting the sugars field in the database.
	FieldSugars = "sugars"
	// FieldSodium holds the string denoting the sodium field in the database.
	FieldSodium = "sodium"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// EdgeOriginalSource holds the string denoting the original_source edge name in mutations.
	EdgeOriginalSource = "original_source"
	// EdgeForks holds the string denoting the forks edge name in mutations.
	EdgeForks = "forks"
	// EdgeUserLogs holds the string denoting the user_logs edge name in mutations.
	EdgeUserLogs = "user_logs"
	// Table holds the table name of the product in the database.
	Table = "products"
	// OriginalSourceTable is the table that holds the original_source relation/edge.
	OriginalSourceTable = "products"
	// OriginalSourceColumn is the table column denoting the original_source relation/edge.
	OriginalSourceColumn = "parent_id"
	// ForksTable is the table that holds the forks relation/edge.
	ForksTable = "products"
	// ForksColumn is the table column denoting the forks relation/edge.
	ForksColumn = "parent_id"
	// UserLogsTable is the table that holds the user_logs relation/edge.
	UserLogsTable = "user_logs"
	// UserLogsInverseTable is the table name for the UserLog entity.
	// It exists in this package in order to avoid circular dependency with the "userlog" package.
	UserLogsInverseTable = "user_logs"
	// UserLogsColumn is the table column denoting the user_logs relation/edge.
	UserLogsColumn = "product_id"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldBarcode,
	FieldName,
	FieldBrand,
	FieldCalories,
	FieldProtein,
	FieldFat,
	FieldSaturatedFat,
	FieldCarbohydrates,
	FieldFiber,
	FieldSugars,
	FieldSodium,
	FieldOwnerID,
	FieldParentID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CaloriesValidator is a validator for the "calories" field. It is called by the builders before save.
	CaloriesValidator func(float64) error
	// ProteinValidator is a validator for the "protein" field. It is called by the builders before save.
	ProteinValidator func(float64) error
	// FatValidator is a validator for the "fat" field. It is called by the builders before save.
	FatValidator func(float64) error
	// SaturatedFatValidator is a validator for the "saturated_fat" field. It is called by the builders before save.
	SaturatedFatValidator func(float64) error
	// CarbohydratesValidator is a validator for the "carbohydrates" field. It is called by the builders before save.
	CarbohydratesValidator func(float64) error
	// FiberValidator is a validator for the "fiber" field. It is called by the builders before save.
	FiberValidator func(float64) error
	// SugarsValidator is a validator for the "sugars" field. It is called by the builders before save.
	SugarsValidator func(float64) error
	// SodiumValidator is a validator for the "sodium" field. It is called by the builders before save.
	SodiumValidator func(float64) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Product queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBarcode orders the results by the barcode field.
func ByBarcode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBarcode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByBrand orders the results by the brand field.
func ByBrand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrand, opts...).ToFunc()
}

// ByCalories orders the results by the calories field.
func ByCalories(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCalories, opts...).ToFunc()
}

// ByProtein orders the results by the protein field.
func ByProtein(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtein, opts...).ToFunc()
}

// ByFat orders the results by the fat field.
func ByFat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFat, opts...).ToFunc()
}

// BySaturatedFat orders the results by the saturated_fat field.
func BySaturatedFat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSaturatedFat, opts...).ToFunc()
}

// ByCarbohydrates orders the results by the carbohydrates field.
func ByCarbohydrates(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCarbohydrates, opts...).ToFunc()
}

// ByFiber orders the results by the fiber field.
func ByFiber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFiber, opts...).ToFunc()
}

// BySugars orders the results by the sugars field.
func BySugars(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSugars, opts...).ToFunc()
}

// BySodium orders the results by the sodium field.
func BySodium(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSodium, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByParentID orders the results by the parent_id field.
func ByParentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentID, opts...).ToFunc()
}

// ByOriginalSourceField orders the results by original_source field.
func ByOriginalSourceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOriginalSourceStep(), sql.OrderByField(field, opts...))
	}
}

// ByForksCount orders the results by forks count.
func ByForksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newForksStep(), opts...)
	}
}

// ByForks orders the results by forks terms.
func ByForks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newForksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserLogsCount orders the results by user_logs count.
func ByUserLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserLogsStep(), opts...)
	}
}

// ByUserLogs orders the results by user_logs terms.
func ByUserLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOriginalSourceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OriginalSourceTable, OriginalSourceColumn),
	)
}
func newForksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ForksTable, ForksColumn),
	)
}
func newUserLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserLogsTable, UserLogsColumn),
	)
}
