// Code generated by ent, DO NOT EDIT.

package product

import (
	"devarminas/kcal-track-api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldID, id))
}

// Barcode applies equality check predicate on the "barcode" field. It's identical to BarcodeEQ.
func Barcode(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldBarcode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldName, v))
}

// Brand applies equality check predicate on the "brand" field. It's identical to BrandEQ.
func Brand(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldBrand, v))
}

// Calories applies equality check predicate on the "calories" field. It's identical to CaloriesEQ.
func Calories(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCalories, v))
}

// Protein applies equality check predicate on the "protein" field. It's identical to ProteinEQ.
func Protein(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldProtein, v))
}

// Fat applies equality check predicate on the "fat" field. It's identical to FatEQ.
func Fat(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldFat, v))
}

// SaturatedFat applies equality check predicate on the "saturated_fat" field. It's identical to SaturatedFatEQ.
func SaturatedFat(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldSaturatedFat, v))
}

// Carbohydrates applies equality check predicate on the "carbohydrates" field. It's identical to CarbohydratesEQ.
func Carbohydrates(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCarbohydrates, v))
}

// Fiber applies equality check predicate on the "fiber" field. It's identical to FiberEQ.
func Fiber(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldFiber, v))
}

// Sugars applies equality check predicate on the "sugars" field. It's identical to SugarsEQ.
func Sugars(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldSugars, v))
}

// Sodium applies equality check predicate on the "sodium" field. It's identical to SodiumEQ.
func Sodium(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldSodium, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCreatedBy, v))
}

// BarcodeEQ applies the EQ predicate on the "barcode" field.
func BarcodeEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldBarcode, v))
}

// BarcodeNEQ applies the NEQ predicate on the "barcode" field.
func BarcodeNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldBarcode, v))
}

// BarcodeIn applies the In predicate on the "barcode" field.
func BarcodeIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldBarcode, vs...))
}

// BarcodeNotIn applies the NotIn predicate on the "barcode" field.
func BarcodeNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldBarcode, vs...))
}

// BarcodeGT applies the GT predicate on the "barcode" field.
func BarcodeGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldBarcode, v))
}

// BarcodeGTE applies the GTE predicate on the "barcode" field.
func BarcodeGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldBarcode, v))
}

// BarcodeLT applies the LT predicate on the "barcode" field.
func BarcodeLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldBarcode, v))
}

// BarcodeLTE applies the LTE predicate on the "barcode" field.
func BarcodeLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldBarcode, v))
}

// BarcodeContains applies the Contains predicate on the "barcode" field.
func BarcodeContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldBarcode, v))
}

// BarcodeHasPrefix applies the HasPrefix predicate on the "barcode" field.
func BarcodeHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldBarcode, v))
}

// BarcodeHasSuffix applies the HasSuffix predicate on the "barcode" field.
func BarcodeHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldBarcode, v))
}

// BarcodeIsNil applies the IsNil predicate on the "barcode" field.
func BarcodeIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldBarcode))
}

// BarcodeNotNil applies the NotNil predicate on the "barcode" field.
func BarcodeNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldBarcode))
}

// BarcodeEqualFold applies the EqualFold predicate on the "barcode" field.
func BarcodeEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldBarcode, v))
}

// BarcodeContainsFold applies the ContainsFold predicate on the "barcode" field.
func BarcodeContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldBarcode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldName, v))
}

// BrandEQ applies the EQ predicate on the "brand" field.
func BrandEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldBrand, v))
}

// BrandNEQ applies the NEQ predicate on the "brand" field.
func BrandNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldBrand, v))
}

// BrandIn applies the In predicate on the "brand" field.
func BrandIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldBrand, vs...))
}

// BrandNotIn applies the NotIn predicate on the "brand" field.
func BrandNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldBrand, vs...))
}

// BrandGT applies the GT predicate on the "brand" field.
func BrandGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldBrand, v))
}

// BrandGTE applies the GTE predicate on the "brand" field.
func BrandGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldBrand, v))
}

// BrandLT applies the LT predicate on the "brand" field.
func BrandLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldBrand, v))
}

// BrandLTE applies the LTE predicate on the "brand" field.
func BrandLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldBrand, v))
}

// BrandContains applies the Contains predicate on the "brand" field.
func BrandContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldBrand, v))
}

// BrandHasPrefix applies the HasPrefix predicate on the "brand" field.
func BrandHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldBrand, v))
}

// BrandHasSuffix applies the HasSuffix predicate on the "brand" field.
func BrandHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldBrand, v))
}

// BrandIsNil applies the IsNil predicate on the "brand" field.
func BrandIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldBrand))
}

// BrandNotNil applies the NotNil predicate on the "brand" field.
func BrandNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldBrand))
}

// BrandEqualFold applies the EqualFold predicate on the "brand" field.
func BrandEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldBrand, v))
}

// BrandContainsFold applies the ContainsFold predicate on the "brand" field.
func BrandContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldBrand, v))
}

// CaloriesEQ applies the EQ predicate on the "calories" field.
func CaloriesEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCalories, v))
}

// CaloriesNEQ applies the NEQ predicate on the "calories" field.
func CaloriesNEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldCalories, v))
}

// CaloriesIn applies the In predicate on the "calories" field.
func CaloriesIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldCalories, vs...))
}

// CaloriesNotIn applies the NotIn predicate on the "calories" field.
func CaloriesNotIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldCalories, vs...))
}

// CaloriesGT applies the GT predicate on the "calories" field.
func CaloriesGT(v float64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldCalories, v))
}

// CaloriesGTE applies the GTE predicate on the "calories" field.
func CaloriesGTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldCalories, v))
}

// CaloriesLT applies the LT predicate on the "calories" field.
func CaloriesLT(v float64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldCalories, v))
}

// CaloriesLTE applies the LTE predicate on the "calories" field.
func CaloriesLTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldCalories, v))
}

// ProteinEQ applies the EQ predicate on the "protein" field.
func ProteinEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldProtein, v))
}

// ProteinNEQ applies the NEQ predicate on the "protein" field.
func ProteinNEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldProtein, v))
}

// ProteinIn applies the In predicate on the "protein" field.
func ProteinIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldProtein, vs...))
}

// ProteinNotIn applies the NotIn predicate on the "protein" field.
func ProteinNotIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldProtein, vs...))
}

// ProteinGT applies the GT predicate on the "protein" field.
func ProteinGT(v float64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldProtein, v))
}

// ProteinGTE applies the GTE predicate on the "protein" field.
func ProteinGTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldProtein, v))
}

// ProteinLT applies the LT predicate on the "protein" field.
func ProteinLT(v float64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldProtein, v))
}

// ProteinLTE applies the LTE predicate on the "protein" field.
func ProteinLTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldProtein, v))
}

// FatEQ applies the EQ predicate on the "fat" field.
func FatEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldFat, v))
}

// FatNEQ applies the NEQ predicate on the "fat" field.
func FatNEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldFat, v))
}

// FatIn applies the In predicate on the "fat" field.
func FatIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldFat, vs...))
}

// FatNotIn applies the NotIn predicate on the "fat" field.
func FatNotIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldFat, vs...))
}

// FatGT applies the GT predicate on the "fat" field.
func FatGT(v float64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldFat, v))
}

// FatGTE applies the GTE predicate on the "fat" field.
func FatGTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldFat, v))
}

// FatLT applies the LT predicate on the "fat" field.
func FatLT(v float64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldFat, v))
}

// FatLTE applies the LTE predicate on the "fat" field.
func FatLTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldFat, v))
}

// SaturatedFatEQ applies the EQ predicate on the "saturated_fat" field.
func SaturatedFatEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldSaturatedFat, v))
}

// SaturatedFatNEQ applies the NEQ predicate on the "saturated_fat" field.
func SaturatedFatNEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldSaturatedFat, v))
}

// SaturatedFatIn applies the In predicate on the "saturated_fat" field.
func SaturatedFatIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldSaturatedFat, vs...))
}

// SaturatedFatNotIn applies the NotIn predicate on the "saturated_fat" field.
func SaturatedFatNotIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldSaturatedFat, vs...))
}

// SaturatedFatGT applies the GT predicate on the "saturated_fat" field.
func SaturatedFatGT(v float64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldSaturatedFat, v))
}

// SaturatedFatGTE applies the GTE predicate on the "saturated_fat" field.
func SaturatedFatGTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldSaturatedFat, v))
}

// SaturatedFatLT applies the LT predicate on the "saturated_fat" field.
func SaturatedFatLT(v float64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldSaturatedFat, v))
}

// SaturatedFatLTE applies the LTE predicate on the "saturated_fat" field.
func SaturatedFatLTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldSaturatedFat, v))
}

// CarbohydratesEQ applies the EQ predicate on the "carbohydrates" field.
func CarbohydratesEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCarbohydrates, v))
}

// CarbohydratesNEQ applies the NEQ predicate on the "carbohydrates" field.
func CarbohydratesNEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldCarbohydrates, v))
}

// CarbohydratesIn applies the In predicate on the "carbohydrates" field.
func CarbohydratesIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldCarbohydrates, vs...))
}

// CarbohydratesNotIn applies the NotIn predicate on the "carbohydrates" field.
func CarbohydratesNotIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldCarbohydrates, vs...))
}

// CarbohydratesGT applies the GT predicate on the "carbohydrates" field.
func CarbohydratesGT(v float64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldCarbohydrates, v))
}

// CarbohydratesGTE applies the GTE predicate on the "carbohydrates" field.
func CarbohydratesGTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldCarbohydrates, v))
}

// CarbohydratesLT applies the LT predicate on the "carbohydrates" field.
func CarbohydratesLT(v float64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldCarbohydrates, v))
}

// CarbohydratesLTE applies the LTE predicate on the "carbohydrates" field.
func CarbohydratesLTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldCarbohydrates, v))
}

// FiberEQ applies the EQ predicate on the "fiber" field.
func FiberEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldFiber, v))
}

// FiberNEQ applies the NEQ predicate on the "fiber" field.
func FiberNEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldFiber, v))
}

// FiberIn applies the In predicate on the "fiber" field.
func FiberIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldFiber, vs...))
}

// FiberNotIn applies the NotIn predicate on the "fiber" field.
func FiberNotIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldFiber, vs...))
}

// FiberGT applies the GT predicate on the "fiber" field.
func FiberGT(v float64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldFiber, v))
}

// FiberGTE applies the GTE predicate on the "fiber" field.
func FiberGTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldFiber, v))
}

// FiberLT applies the LT predicate on the "fiber" field.
func FiberLT(v float64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldFiber, v))
}

// FiberLTE applies the LTE predicate on the "fiber" field.
func FiberLTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldFiber, v))
}

// SugarsEQ applies the EQ predicate on the "sugars" field.
func SugarsEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldSugars, v))
}

// SugarsNEQ applies the NEQ predicate on the "sugars" field.
func SugarsNEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldSugars, v))
}

// SugarsIn applies the In predicate on the "sugars" field.
func SugarsIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldSugars, vs...))
}

// SugarsNotIn applies the NotIn predicate on the "sugars" field.
func SugarsNotIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldSugars, vs...))
}

// SugarsGT applies the GT predicate on the "sugars" field.
func SugarsGT(v float64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldSugars, v))
}

// SugarsGTE applies the GTE predicate on the "sugars" field.
func SugarsGTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldSugars, v))
}

// SugarsLT applies the LT predicate on the "sugars" field.
func SugarsLT(v float64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldSugars, v))
}

// SugarsLTE applies the LTE predicate on the "sugars" field.
func SugarsLTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldSugars, v))
}

// SodiumEQ applies the EQ predicate on the "sodium" field.
func SodiumEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldSodium, v))
}

// SodiumNEQ applies the NEQ predicate on the "sodium" field.
func SodiumNEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldSodium, v))
}

// SodiumIn applies the In predicate on the "sodium" field.
func SodiumIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldSodium, vs...))
}

// SodiumNotIn applies the NotIn predicate on the "sodium" field.
func SodiumNotIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldSodium, vs...))
}

// SodiumGT applies the GT predicate on the "sodium" field.
func SodiumGT(v float64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldSodium, v))
}

// SodiumGTE applies the GTE predicate on the "sodium" field.
func SodiumGTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldSodium, v))
}

// SodiumLT applies the LT predicate on the "sodium" field.
func SodiumLT(v float64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldSodium, v))
}

// SodiumLTE applies the LTE predicate on the "sodium" field.
func SodiumLTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldSodium, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldCreatedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Product) predicate.Product {
	return predicate.Product(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Product) predicate.Product {
	return predicate.Product(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Product) predicate.Product {
	return predicate.Product(sql.NotPredicates(p))
}
