// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "barcode", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "brand", Type: field.TypeString, Nullable: true},
		{Name: "calories", Type: field.TypeFloat64},
		{Name: "protein", Type: field.TypeFloat64},
		{Name: "fat", Type: field.TypeFloat64},
		{Name: "saturated_fat", Type: field.TypeFloat64},
		{Name: "carbohydrates", Type: field.TypeFloat64},
		{Name: "fiber", Type: field.TypeFloat64},
		{Name: "sugars", Type: field.TypeFloat64},
		{Name: "sodium", Type: field.TypeFloat64},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProductsTable,
	}
)

func init() {
}
