// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"devarminas/kcal-track-api/ent/predicate"
	"devarminas/kcal-track-api/ent/product"
	"devarminas/kcal-track-api/ent/userlog"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeProduct = "Product"
	TypeUserLog = "UserLog"
)

// ProductMutation represents an operation that mutates the Product nodes in the graph.
type ProductMutation struct {
	config
	op                     Op
	typ                    string
	id                     *uuid.UUID
	barcode                *string
	name                   *string
	brand                  *string
	calories               *float64
	addcalories            *float64
	protein                *float64
	addprotein             *float64
	fat                    *float64
	addfat                 *float64
	saturated_fat          *float64
	addsaturated_fat       *float64
	carbohydrates          *float64
	addcarbohydrates       *float64
	fiber                  *float64
	addfiber               *float64
	sugars                 *float64
	addsugars              *float64
	sodium                 *float64
	addsodium              *float64
	owner_id               *string
	clearedFields          map[string]struct{}
	original_source        *uuid.UUID
	clearedoriginal_source bool
	forks                  map[uuid.UUID]struct{}
	removedforks           map[uuid.UUID]struct{}
	clearedforks           bool
	user_logs              map[uuid.UUID]struct{}
	removeduser_logs       map[uuid.UUID]struct{}
	cleareduser_logs       bool
	done                   bool
	oldValue               func(context.Context) (*Product, error)
	predicates             []predicate.Product
}

var _ ent.Mutation = (*ProductMutation)(nil)

// productOption allows management of the mutation configuration using functional options.
type productOption func(*ProductMutation)

// newProductMutation creates new mutation for the Product entity.
func newProductMutation(c config, op Op, opts ...productOption) *ProductMutation {
	m := &ProductMutation{
		config:        c,
		op:            op,
		typ:           TypeProduct,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withProductID sets the ID field of the mutation.
func withProductID(id uuid.UUID) productOption {
	return func(m *ProductMutation) {
		var (
			err   error
			once  sync.Once
			value *Product
		)
		m.oldValue = func(ctx context.Context) (*Product, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Product.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withProduct sets the old Product of the mutation.
func withProduct(node *Product) productOption {
	return func(m *ProductMutation) {
		m.oldValue = func(context.Context) (*Product, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ProductMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ProductMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Product entities.
func (m *ProductMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ProductMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ProductMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Product.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetBarcode sets the "barcode" field.
func (m *ProductMutation) SetBarcode(s string) {
	m.barcode = &s
}

// Barcode returns the value of the "barcode" field in the mutation.
func (m *ProductMutation) Barcode() (r string, exists bool) {
	v := m.barcode
	if v == nil {
		return
	}
	return *v, true
}

// OldBarcode returns the old "barcode" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldBarcode(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBarcode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBarcode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBarcode: %w", err)
	}
	return oldValue.Barcode, nil
}

// ClearBarcode clears the value of the "barcode" field.
func (m *ProductMutation) ClearBarcode() {
	m.barcode = nil
	m.clearedFields[product.FieldBarcode] = struct{}{}
}

// BarcodeCleared returns if the "barcode" field was cleared in this mutation.
func (m *ProductMutation) BarcodeCleared() bool {
	_, ok := m.clearedFields[product.FieldBarcode]
	return ok
}

// ResetBarcode resets all changes to the "barcode" field.
func (m *ProductMutation) ResetBarcode() {
	m.barcode = nil
	delete(m.clearedFields, product.FieldBarcode)
}

// SetName sets the "name" field.
func (m *ProductMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ProductMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ProductMutation) ResetName() {
	m.name = nil
}

// SetBrand sets the "brand" field.
func (m *ProductMutation) SetBrand(s string) {
	m.brand = &s
}

// Brand returns the value of the "brand" field in the mutation.
func (m *ProductMutation) Brand() (r string, exists bool) {
	v := m.brand
	if v == nil {
		return
	}
	return *v, true
}

// OldBrand returns the old "brand" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldBrand(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBrand is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBrand requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBrand: %w", err)
	}
	return oldValue.Brand, nil
}

// ClearBrand clears the value of the "brand" field.
func (m *ProductMutation) ClearBrand() {
	m.brand = nil
	m.clearedFields[product.FieldBrand] = struct{}{}
}

// BrandCleared returns if the "brand" field was cleared in this mutation.
func (m *ProductMutation) BrandCleared() bool {
	_, ok := m.clearedFields[product.FieldBrand]
	return ok
}

// ResetBrand resets all changes to the "brand" field.
func (m *ProductMutation) ResetBrand() {
	m.brand = nil
	delete(m.clearedFields, product.FieldBrand)
}

// SetCalories sets the "calories" field.
func (m *ProductMutation) SetCalories(f float64) {
	m.calories = &f
	m.addcalories = nil
}

// Calories returns the value of the "calories" field in the mutation.
func (m *ProductMutation) Calories() (r float64, exists bool) {
	v := m.calories
	if v == nil {
		return
	}
	return *v, true
}

// OldCalories returns the old "calories" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldCalories(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCalories is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCalories requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCalories: %w", err)
	}
	return oldValue.Calories, nil
}

// AddCalories adds f to the "calories" field.
func (m *ProductMutation) AddCalories(f float64) {
	if m.addcalories != nil {
		*m.addcalories += f
	} else {
		m.addcalories = &f
	}
}

// AddedCalories returns the value that was added to the "calories" field in this mutation.
func (m *ProductMutation) AddedCalories() (r float64, exists bool) {
	v := m.addcalories
	if v == nil {
		return
	}
	return *v, true
}

// ResetCalories resets all changes to the "calories" field.
func (m *ProductMutation) ResetCalories() {
	m.calories = nil
	m.addcalories = nil
}

// SetProtein sets the "protein" field.
func (m *ProductMutation) SetProtein(f float64) {
	m.protein = &f
	m.addprotein = nil
}

// Protein returns the value of the "protein" field in the mutation.
func (m *ProductMutation) Protein() (r float64, exists bool) {
	v := m.protein
	if v == nil {
		return
	}
	return *v, true
}

// OldProtein returns the old "protein" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldProtein(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProtein is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProtein requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProtein: %w", err)
	}
	return oldValue.Protein, nil
}

// AddProtein adds f to the "protein" field.
func (m *ProductMutation) AddProtein(f float64) {
	if m.addprotein != nil {
		*m.addprotein += f
	} else {
		m.addprotein = &f
	}
}

// AddedProtein returns the value that was added to the "protein" field in this mutation.
func (m *ProductMutation) AddedProtein() (r float64, exists bool) {
	v := m.addprotein
	if v == nil {
		return
	}
	return *v, true
}

// ResetProtein resets all changes to the "protein" field.
func (m *ProductMutation) ResetProtein() {
	m.protein = nil
	m.addprotein = nil
}

// SetFat sets the "fat" field.
func (m *ProductMutation) SetFat(f float64) {
	m.fat = &f
	m.addfat = nil
}

// Fat returns the value of the "fat" field in the mutation.
func (m *ProductMutation) Fat() (r float64, exists bool) {
	v := m.fat
	if v == nil {
		return
	}
	return *v, true
}

// OldFat returns the old "fat" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldFat(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFat is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFat requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFat: %w", err)
	}
	return oldValue.Fat, nil
}

// AddFat adds f to the "fat" field.
func (m *ProductMutation) AddFat(f float64) {
	if m.addfat != nil {
		*m.addfat += f
	} else {
		m.addfat = &f
	}
}

// AddedFat returns the value that was added to the "fat" field in this mutation.
func (m *ProductMutation) AddedFat() (r float64, exists bool) {
	v := m.addfat
	if v == nil {
		return
	}
	return *v, true
}

// ResetFat resets all changes to the "fat" field.
func (m *ProductMutation) ResetFat() {
	m.fat = nil
	m.addfat = nil
}

// SetSaturatedFat sets the "saturated_fat" field.
func (m *ProductMutation) SetSaturatedFat(f float64) {
	m.saturated_fat = &f
	m.addsaturated_fat = nil
}

// SaturatedFat returns the value of the "saturated_fat" field in the mutation.
func (m *ProductMutation) SaturatedFat() (r float64, exists bool) {
	v := m.saturated_fat
	if v == nil {
		return
	}
	return *v, true
}

// OldSaturatedFat returns the old "saturated_fat" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldSaturatedFat(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSaturatedFat is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSaturatedFat requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSaturatedFat: %w", err)
	}
	return oldValue.SaturatedFat, nil
}

// AddSaturatedFat adds f to the "saturated_fat" field.
func (m *ProductMutation) AddSaturatedFat(f float64) {
	if m.addsaturated_fat != nil {
		*m.addsaturated_fat += f
	} else {
		m.addsaturated_fat = &f
	}
}

// AddedSaturatedFat returns the value that was added to the "saturated_fat" field in this mutation.
func (m *ProductMutation) AddedSaturatedFat() (r float64, exists bool) {
	v := m.addsaturated_fat
	if v == nil {
		return
	}
	return *v, true
}

// ResetSaturatedFat resets all changes to the "saturated_fat" field.
func (m *ProductMutation) ResetSaturatedFat() {
	m.saturated_fat = nil
	m.addsaturated_fat = nil
}

// SetCarbohydrates sets the "carbohydrates" field.
func (m *ProductMutation) SetCarbohydrates(f float64) {
	m.carbohydrates = &f
	m.addcarbohydrates = nil
}

// Carbohydrates returns the value of the "carbohydrates" field in the mutation.
func (m *ProductMutation) Carbohydrates() (r float64, exists bool) {
	v := m.carbohydrates
	if v == nil {
		return
	}
	return *v, true
}

// OldCarbohydrates returns the old "carbohydrates" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldCarbohydrates(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCarbohydrates is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCarbohydrates requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCarbohydrates: %w", err)
	}
	return oldValue.Carbohydrates, nil
}

// AddCarbohydrates adds f to the "carbohydrates" field.
func (m *ProductMutation) AddCarbohydrates(f float64) {
	if m.addcarbohydrates != nil {
		*m.addcarbohydrates += f
	} else {
		m.addcarbohydrates = &f
	}
}

// AddedCarbohydrates returns the value that was added to the "carbohydrates" field in this mutation.
func (m *ProductMutation) AddedCarbohydrates() (r float64, exists bool) {
	v := m.addcarbohydrates
	if v == nil {
		return
	}
	return *v, true
}

// ResetCarbohydrates resets all changes to the "carbohydrates" field.
func (m *ProductMutation) ResetCarbohydrates() {
	m.carbohydrates = nil
	m.addcarbohydrates = nil
}

// SetFiber sets the "fiber" field.
func (m *ProductMutation) SetFiber(f float64) {
	m.fiber = &f
	m.addfiber = nil
}

// Fiber returns the value of the "fiber" field in the mutation.
func (m *ProductMutation) Fiber() (r float64, exists bool) {
	v := m.fiber
	if v == nil {
		return
	}
	return *v, true
}

// OldFiber returns the old "fiber" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldFiber(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFiber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFiber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFiber: %w", err)
	}
	return oldValue.Fiber, nil
}

// AddFiber adds f to the "fiber" field.
func (m *ProductMutation) AddFiber(f float64) {
	if m.addfiber != nil {
		*m.addfiber += f
	} else {
		m.addfiber = &f
	}
}

// AddedFiber returns the value that was added to the "fiber" field in this mutation.
func (m *ProductMutation) AddedFiber() (r float64, exists bool) {
	v := m.addfiber
	if v == nil {
		return
	}
	return *v, true
}

// ResetFiber resets all changes to the "fiber" field.
func (m *ProductMutation) ResetFiber() {
	m.fiber = nil
	m.addfiber = nil
}

// SetSugars sets the "sugars" field.
func (m *ProductMutation) SetSugars(f float64) {
	m.sugars = &f
	m.addsugars = nil
}

// Sugars returns the value of the "sugars" field in the mutation.
func (m *ProductMutation) Sugars() (r float64, exists bool) {
	v := m.sugars
	if v == nil {
		return
	}
	return *v, true
}

// OldSugars returns the old "sugars" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldSugars(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSugars is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSugars requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSugars: %w", err)
	}
	return oldValue.Sugars, nil
}

// AddSugars adds f to the "sugars" field.
func (m *ProductMutation) AddSugars(f float64) {
	if m.addsugars != nil {
		*m.addsugars += f
	} else {
		m.addsugars = &f
	}
}

// AddedSugars returns the value that was added to the "sugars" field in this mutation.
func (m *ProductMutation) AddedSugars() (r float64, exists bool) {
	v := m.addsugars
	if v == nil {
		return
	}
	return *v, true
}

// ResetSugars resets all changes to the "sugars" field.
func (m *ProductMutation) ResetSugars() {
	m.sugars = nil
	m.addsugars = nil
}

// SetSodium sets the "sodium" field.
func (m *ProductMutation) SetSodium(f float64) {
	m.sodium = &f
	m.addsodium = nil
}

// Sodium returns the value of the "sodium" field in the mutation.
func (m *ProductMutation) Sodium() (r float64, exists bool) {
	v := m.sodium
	if v == nil {
		return
	}
	return *v, true
}

// OldSodium returns the old "sodium" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldSodium(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSodium is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSodium requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSodium: %w", err)
	}
	return oldValue.Sodium, nil
}

// AddSodium adds f to the "sodium" field.
func (m *ProductMutation) AddSodium(f float64) {
	if m.addsodium != nil {
		*m.addsodium += f
	} else {
		m.addsodium = &f
	}
}

// AddedSodium returns the value that was added to the "sodium" field in this mutation.
func (m *ProductMutation) AddedSodium() (r float64, exists bool) {
	v := m.addsodium
	if v == nil {
		return
	}
	return *v, true
}

// ResetSodium resets all changes to the "sodium" field.
func (m *ProductMutation) ResetSodium() {
	m.sodium = nil
	m.addsodium = nil
}

// SetOwnerID sets the "owner_id" field.
func (m *ProductMutation) SetOwnerID(s string) {
	m.owner_id = &s
}

// OwnerID returns the value of the "owner_id" field in the mutation.
func (m *ProductMutation) OwnerID() (r string, exists bool) {
	v := m.owner_id
	if v == nil {
		return
	}
	return *v, true
}

// OldOwnerID returns the old "owner_id" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldOwnerID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOwnerID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOwnerID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOwnerID: %w", err)
	}
	return oldValue.OwnerID, nil
}

// ClearOwnerID clears the value of the "owner_id" field.
func (m *ProductMutation) ClearOwnerID() {
	m.owner_id = nil
	m.clearedFields[product.FieldOwnerID] = struct{}{}
}

// OwnerIDCleared returns if the "owner_id" field was cleared in this mutation.
func (m *ProductMutation) OwnerIDCleared() bool {
	_, ok := m.clearedFields[product.FieldOwnerID]
	return ok
}

// ResetOwnerID resets all changes to the "owner_id" field.
func (m *ProductMutation) ResetOwnerID() {
	m.owner_id = nil
	delete(m.clearedFields, product.FieldOwnerID)
}

// SetParentID sets the "parent_id" field.
func (m *ProductMutation) SetParentID(u uuid.UUID) {
	m.original_source = &u
}

// ParentID returns the value of the "parent_id" field in the mutation.
func (m *ProductMutation) ParentID() (r uuid.UUID, exists bool) {
	v := m.original_source
	if v == nil {
		return
	}
	return *v, true
}

// OldParentID returns the old "parent_id" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldParentID(ctx context.Context) (v *uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldParentID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldParentID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldParentID: %w", err)
	}
	return oldValue.ParentID, nil
}

// ClearParentID clears the value of the "parent_id" field.
func (m *ProductMutation) ClearParentID() {
	m.original_source = nil
	m.clearedFields[product.FieldParentID] = struct{}{}
}

// ParentIDCleared returns if the "parent_id" field was cleared in this mutation.
func (m *ProductMutation) ParentIDCleared() bool {
	_, ok := m.clearedFields[product.FieldParentID]
	return ok
}

// ResetParentID resets all changes to the "parent_id" field.
func (m *ProductMutation) ResetParentID() {
	m.original_source = nil
	delete(m.clearedFields, product.FieldParentID)
}

// SetOriginalSourceID sets the "original_source" edge to the Product entity by id.
func (m *ProductMutation) SetOriginalSourceID(id uuid.UUID) {
	m.original_source = &id
}

// ClearOriginalSource clears the "original_source" edge to the Product entity.
func (m *ProductMutation) ClearOriginalSource() {
	m.clearedoriginal_source = true
	m.clearedFields[product.FieldParentID] = struct{}{}
}

// OriginalSourceCleared reports if the "original_source" edge to the Product entity was cleared.
func (m *ProductMutation) OriginalSourceCleared() bool {
	return m.ParentIDCleared() || m.clearedoriginal_source
}

// OriginalSourceID returns the "original_source" edge ID in the mutation.
func (m *ProductMutation) OriginalSourceID() (id uuid.UUID, exists bool) {
	if m.original_source != nil {
		return *m.original_source, true
	}
	return
}

// OriginalSourceIDs returns the "original_source" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// OriginalSourceID instead. It exists only for internal usage by the builders.
func (m *ProductMutation) OriginalSourceIDs() (ids []uuid.UUID) {
	if id := m.original_source; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetOriginalSource resets all changes to the "original_source" edge.
func (m *ProductMutation) ResetOriginalSource() {
	m.original_source = nil
	m.clearedoriginal_source = false
}

// AddForkIDs adds the "forks" edge to the Product entity by ids.
func (m *ProductMutation) AddForkIDs(ids ...uuid.UUID) {
	if m.forks == nil {
		m.forks = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.forks[ids[i]] = struct{}{}
	}
}

// ClearForks clears the "forks" edge to the Product entity.
func (m *ProductMutation) ClearForks() {
	m.clearedforks = true
}

// ForksCleared reports if the "forks" edge to the Product entity was cleared.
func (m *ProductMutation) ForksCleared() bool {
	return m.clearedforks
}

// RemoveForkIDs removes the "forks" edge to the Product entity by IDs.
func (m *ProductMutation) RemoveForkIDs(ids ...uuid.UUID) {
	if m.removedforks == nil {
		m.removedforks = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.forks, ids[i])
		m.removedforks[ids[i]] = struct{}{}
	}
}

// RemovedForks returns the removed IDs of the "forks" edge to the Product entity.
func (m *ProductMutation) RemovedForksIDs() (ids []uuid.UUID) {
	for id := range m.removedforks {
		ids = append(ids, id)
	}
	return
}

// ForksIDs returns the "forks" edge IDs in the mutation.
func (m *ProductMutation) ForksIDs() (ids []uuid.UUID) {
	for id := range m.forks {
		ids = append(ids, id)
	}
	return
}

// ResetForks resets all changes to the "forks" edge.
func (m *ProductMutation) ResetForks() {
	m.forks = nil
	m.clearedforks = false
	m.removedforks = nil
}

// AddUserLogIDs adds the "user_logs" edge to the UserLog entity by ids.
func (m *ProductMutation) AddUserLogIDs(ids ...uuid.UUID) {
	if m.user_logs == nil {
		m.user_logs = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.user_logs[ids[i]] = struct{}{}
	}
}

// ClearUserLogs clears the "user_logs" edge to the UserLog entity.
func (m *ProductMutation) ClearUserLogs() {
	m.cleareduser_logs = true
}

// UserLogsCleared reports if the "user_logs" edge to the UserLog entity was cleared.
func (m *ProductMutation) UserLogsCleared() bool {
	return m.cleareduser_logs
}

// RemoveUserLogIDs removes the "user_logs" edge to the UserLog entity by IDs.
func (m *ProductMutation) RemoveUserLogIDs(ids ...uuid.UUID) {
	if m.removeduser_logs == nil {
		m.removeduser_logs = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.user_logs, ids[i])
		m.removeduser_logs[ids[i]] = struct{}{}
	}
}

// RemovedUserLogs returns the removed IDs of the "user_logs" edge to the UserLog entity.
func (m *ProductMutation) RemovedUserLogsIDs() (ids []uuid.UUID) {
	for id := range m.removeduser_logs {
		ids = append(ids, id)
	}
	return
}

// UserLogsIDs returns the "user_logs" edge IDs in the mutation.
func (m *ProductMutation) UserLogsIDs() (ids []uuid.UUID) {
	for id := range m.user_logs {
		ids = append(ids, id)
	}
	return
}

// ResetUserLogs resets all changes to the "user_logs" edge.
func (m *ProductMutation) ResetUserLogs() {
	m.user_logs = nil
	m.cleareduser_logs = false
	m.removeduser_logs = nil
}

// Where appends a list predicates to the ProductMutation builder.
func (m *ProductMutation) Where(ps ...predicate.Product) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ProductMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ProductMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Product, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ProductMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ProductMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Product).
func (m *ProductMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ProductMutation) Fields() []string {
	fields := make([]string, 0, 13)
	if m.barcode != nil {
		fields = append(fields, product.FieldBarcode)
	}
	if m.name != nil {
		fields = append(fields, product.FieldName)
	}
	if m.brand != nil {
		fields = append(fields, product.FieldBrand)
	}
	if m.calories != nil {
		fields = append(fields, product.FieldCalories)
	}
	if m.protein != nil {
		fields = append(fields, product.FieldProtein)
	}
	if m.fat != nil {
		fields = append(fields, product.FieldFat)
	}
	if m.saturated_fat != nil {
		fields = append(fields, product.FieldSaturatedFat)
	}
	if m.carbohydrates != nil {
		fields = append(fields, product.FieldCarbohydrates)
	}
	if m.fiber != nil {
		fields = append(fields, product.FieldFiber)
	}
	if m.sugars != nil {
		fields = append(fields, product.FieldSugars)
	}
	if m.sodium != nil {
		fields = append(fields, product.FieldSodium)
	}
	if m.owner_id != nil {
		fields = append(fields, product.FieldOwnerID)
	}
	if m.original_source != nil {
		fields = append(fields, product.FieldParentID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ProductMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case product.FieldBarcode:
		return m.Barcode()
	case product.FieldName:
		return m.Name()
	case product.FieldBrand:
		return m.Brand()
	case product.FieldCalories:
		return m.Calories()
	case product.FieldProtein:
		return m.Protein()
	case product.FieldFat:
		return m.Fat()
	case product.FieldSaturatedFat:
		return m.SaturatedFat()
	case product.FieldCarbohydrates:
		return m.Carbohydrates()
	case product.FieldFiber:
		return m.Fiber()
	case product.FieldSugars:
		return m.Sugars()
	case product.FieldSodium:
		return m.Sodium()
	case product.FieldOwnerID:
		return m.OwnerID()
	case product.FieldParentID:
		return m.ParentID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ProductMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case product.FieldBarcode:
		return m.OldBarcode(ctx)
	case product.FieldName:
		return m.OldName(ctx)
	case product.FieldBrand:
		return m.OldBrand(ctx)
	case product.FieldCalories:
		return m.OldCalories(ctx)
	case product.FieldProtein:
		return m.OldProtein(ctx)
	case product.FieldFat:
		return m.OldFat(ctx)
	case product.FieldSaturatedFat:
		return m.OldSaturatedFat(ctx)
	case product.FieldCarbohydrates:
		return m.OldCarbohydrates(ctx)
	case product.FieldFiber:
		return m.OldFiber(ctx)
	case product.FieldSugars:
		return m.OldSugars(ctx)
	case product.FieldSodium:
		return m.OldSodium(ctx)
	case product.FieldOwnerID:
		return m.OldOwnerID(ctx)
	case product.FieldParentID:
		return m.OldParentID(ctx)
	}
	return nil, fmt.Errorf("unknown Product field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProductMutation) SetField(name string, value ent.Value) error {
	switch name {
	case product.FieldBarcode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBarcode(v)
		return nil
	case product.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case product.FieldBrand:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBrand(v)
		return nil
	case product.FieldCalories:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCalories(v)
		return nil
	case product.FieldProtein:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProtein(v)
		return nil
	case product.FieldFat:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFat(v)
		return nil
	case product.FieldSaturatedFat:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSaturatedFat(v)
		return nil
	case product.FieldCarbohydrates:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCarbohydrates(v)
		return nil
	case product.FieldFiber:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFiber(v)
		return nil
	case product.FieldSugars:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSugars(v)
		return nil
	case product.FieldSodium:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSodium(v)
		return nil
	case product.FieldOwnerID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOwnerID(v)
		return nil
	case product.FieldParentID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetParentID(v)
		return nil
	}
	return fmt.Errorf("unknown Product field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ProductMutation) AddedFields() []string {
	var fields []string
	if m.addcalories != nil {
		fields = append(fields, product.FieldCalories)
	}
	if m.addprotein != nil {
		fields = append(fields, product.FieldProtein)
	}
	if m.addfat != nil {
		fields = append(fields, product.FieldFat)
	}
	if m.addsaturated_fat != nil {
		fields = append(fields, product.FieldSaturatedFat)
	}
	if m.addcarbohydrates != nil {
		fields = append(fields, product.FieldCarbohydrates)
	}
	if m.addfiber != nil {
		fields = append(fields, product.FieldFiber)
	}
	if m.addsugars != nil {
		fields = append(fields, product.FieldSugars)
	}
	if m.addsodium != nil {
		fields = append(fields, product.FieldSodium)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ProductMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case product.FieldCalories:
		return m.AddedCalories()
	case product.FieldProtein:
		return m.AddedProtein()
	case product.FieldFat:
		return m.AddedFat()
	case product.FieldSaturatedFat:
		return m.AddedSaturatedFat()
	case product.FieldCarbohydrates:
		return m.AddedCarbohydrates()
	case product.FieldFiber:
		return m.AddedFiber()
	case product.FieldSugars:
		return m.AddedSugars()
	case product.FieldSodium:
		return m.AddedSodium()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProductMutation) AddField(name string, value ent.Value) error {
	switch name {
	case product.FieldCalories:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCalories(v)
		return nil
	case product.FieldProtein:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddProtein(v)
		return nil
	case product.FieldFat:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddFat(v)
		return nil
	case product.FieldSaturatedFat:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSaturatedFat(v)
		return nil
	case product.FieldCarbohydrates:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCarbohydrates(v)
		return nil
	case product.FieldFiber:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddFiber(v)
		return nil
	case product.FieldSugars:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSugars(v)
		return nil
	case product.FieldSodium:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSodium(v)
		return nil
	}
	return fmt.Errorf("unknown Product numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ProductMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(product.FieldBarcode) {
		fields = append(fields, product.FieldBarcode)
	}
	if m.FieldCleared(product.FieldBrand) {
		fields = append(fields, product.FieldBrand)
	}
	if m.FieldCleared(product.FieldOwnerID) {
		fields = append(fields, product.FieldOwnerID)
	}
	if m.FieldCleared(product.FieldParentID) {
		fields = append(fields, product.FieldParentID)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ProductMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ProductMutation) ClearField(name string) error {
	switch name {
	case product.FieldBarcode:
		m.ClearBarcode()
		return nil
	case product.FieldBrand:
		m.ClearBrand()
		return nil
	case product.FieldOwnerID:
		m.ClearOwnerID()
		return nil
	case product.FieldParentID:
		m.ClearParentID()
		return nil
	}
	return fmt.Errorf("unknown Product nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ProductMutation) ResetField(name string) error {
	switch name {
	case product.FieldBarcode:
		m.ResetBarcode()
		return nil
	case product.FieldName:
		m.ResetName()
		return nil
	case product.FieldBrand:
		m.ResetBrand()
		return nil
	case product.FieldCalories:
		m.ResetCalories()
		return nil
	case product.FieldProtein:
		m.ResetProtein()
		return nil
	case product.FieldFat:
		m.ResetFat()
		return nil
	case product.FieldSaturatedFat:
		m.ResetSaturatedFat()
		return nil
	case product.FieldCarbohydrates:
		m.ResetCarbohydrates()
		return nil
	case product.FieldFiber:
		m.ResetFiber()
		return nil
	case product.FieldSugars:
		m.ResetSugars()
		return nil
	case product.FieldSodium:
		m.ResetSodium()
		return nil
	case product.FieldOwnerID:
		m.ResetOwnerID()
		return nil
	case product.FieldParentID:
		m.ResetParentID()
		return nil
	}
	return fmt.Errorf("unknown Product field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ProductMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.original_source != nil {
		edges = append(edges, product.EdgeOriginalSource)
	}
	if m.forks != nil {
		edges = append(edges, product.EdgeForks)
	}
	if m.user_logs != nil {
		edges = append(edges, product.EdgeUserLogs)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ProductMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case product.EdgeOriginalSource:
		if id := m.original_source; id != nil {
			return []ent.Value{*id}
		}
	case product.EdgeForks:
		ids := make([]ent.Value, 0, len(m.forks))
		for id := range m.forks {
			ids = append(ids, id)
		}
		return ids
	case product.EdgeUserLogs:
		ids := make([]ent.Value, 0, len(m.user_logs))
		for id := range m.user_logs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ProductMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedforks != nil {
		edges = append(edges, product.EdgeForks)
	}
	if m.removeduser_logs != nil {
		edges = append(edges, product.EdgeUserLogs)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ProductMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case product.EdgeForks:
		ids := make([]ent.Value, 0, len(m.removedforks))
		for id := range m.removedforks {
			ids = append(ids, id)
		}
		return ids
	case product.EdgeUserLogs:
		ids := make([]ent.Value, 0, len(m.removeduser_logs))
		for id := range m.removeduser_logs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ProductMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedoriginal_source {
		edges = append(edges, product.EdgeOriginalSource)
	}
	if m.clearedforks {
		edges = append(edges, product.EdgeForks)
	}
	if m.cleareduser_logs {
		edges = append(edges, product.EdgeUserLogs)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ProductMutation) EdgeCleared(name string) bool {
	switch name {
	case product.EdgeOriginalSource:
		return m.clearedoriginal_source
	case product.EdgeForks:
		return m.clearedforks
	case product.EdgeUserLogs:
		return m.cleareduser_logs
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ProductMutation) ClearEdge(name string) error {
	switch name {
	case product.EdgeOriginalSource:
		m.ClearOriginalSource()
		return nil
	}
	return fmt.Errorf("unknown Product unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ProductMutation) ResetEdge(name string) error {
	switch name {
	case product.EdgeOriginalSource:
		m.ResetOriginalSource()
		return nil
	case product.EdgeForks:
		m.ResetForks()
		return nil
	case product.EdgeUserLogs:
		m.ResetUserLogs()
		return nil
	}
	return fmt.Errorf("unknown Product edge %s", name)
}

// UserLogMutation represents an operation that mutates the UserLog nodes in the graph.
type UserLogMutation struct {
	config
	op             Op
	typ            string
	id             *uuid.UUID
	amount         *float64
	addamount      *float64
	date           *time.Time
	user_id        *string
	clearedFields  map[string]struct{}
	product        *uuid.UUID
	clearedproduct bool
	done           bool
	oldValue       func(context.Context) (*UserLog, error)
	predicates     []predicate.UserLog
}

var _ ent.Mutation = (*UserLogMutation)(nil)

// userlogOption allows management of the mutation configuration using functional options.
type userlogOption func(*UserLogMutation)

// newUserLogMutation creates new mutation for the UserLog entity.
func newUserLogMutation(c config, op Op, opts ...userlogOption) *UserLogMutation {
	m := &UserLogMutation{
		config:        c,
		op:            op,
		typ:           TypeUserLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserLogID sets the ID field of the mutation.
func withUserLogID(id uuid.UUID) userlogOption {
	return func(m *UserLogMutation) {
		var (
			err   error
			once  sync.Once
			value *UserLog
		)
		m.oldValue = func(ctx context.Context) (*UserLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().UserLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUserLog sets the old UserLog of the mutation.
func withUserLog(node *UserLog) userlogOption {
	return func(m *UserLogMutation) {
		m.oldValue = func(context.Context) (*UserLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of UserLog entities.
func (m *UserLogMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserLogMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserLogMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().UserLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAmount sets the "amount" field.
func (m *UserLogMutation) SetAmount(f float64) {
	m.amount = &f
	m.addamount = nil
}

// Amount returns the value of the "amount" field in the mutation.
func (m *UserLogMutation) Amount() (r float64, exists bool) {
	v := m.amount
	if v == nil {
		return
	}
	return *v, true
}

// OldAmount returns the old "amount" field's value of the UserLog entity.
// If the UserLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserLogMutation) OldAmount(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAmount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAmount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAmount: %w", err)
	}
	return oldValue.Amount, nil
}

// AddAmount adds f to the "amount" field.
func (m *UserLogMutation) AddAmount(f float64) {
	if m.addamount != nil {
		*m.addamount += f
	} else {
		m.addamount = &f
	}
}

// AddedAmount returns the value that was added to the "amount" field in this mutation.
func (m *UserLogMutation) AddedAmount() (r float64, exists bool) {
	v := m.addamount
	if v == nil {
		return
	}
	return *v, true
}

// ResetAmount resets all changes to the "amount" field.
func (m *UserLogMutation) ResetAmount() {
	m.amount = nil
	m.addamount = nil
}

// SetDate sets the "date" field.
func (m *UserLogMutation) SetDate(t time.Time) {
	m.date = &t
}

// Date returns the value of the "date" field in the mutation.
func (m *UserLogMutation) Date() (r time.Time, exists bool) {
	v := m.date
	if v == nil {
		return
	}
	return *v, true
}

// OldDate returns the old "date" field's value of the UserLog entity.
// If the UserLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserLogMutation) OldDate(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDate: %w", err)
	}
	return oldValue.Date, nil
}

// ResetDate resets all changes to the "date" field.
func (m *UserLogMutation) ResetDate() {
	m.date = nil
}

// SetUserID sets the "user_id" field.
func (m *UserLogMutation) SetUserID(s string) {
	m.user_id = &s
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *UserLogMutation) UserID() (r string, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the UserLog entity.
// If the UserLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserLogMutation) OldUserID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ClearUserID clears the value of the "user_id" field.
func (m *UserLogMutation) ClearUserID() {
	m.user_id = nil
	m.clearedFields[userlog.FieldUserID] = struct{}{}
}

// UserIDCleared returns if the "user_id" field was cleared in this mutation.
func (m *UserLogMutation) UserIDCleared() bool {
	_, ok := m.clearedFields[userlog.FieldUserID]
	return ok
}

// ResetUserID resets all changes to the "user_id" field.
func (m *UserLogMutation) ResetUserID() {
	m.user_id = nil
	delete(m.clearedFields, userlog.FieldUserID)
}

// SetProductID sets the "product_id" field.
func (m *UserLogMutation) SetProductID(u uuid.UUID) {
	m.product = &u
}

// ProductID returns the value of the "product_id" field in the mutation.
func (m *UserLogMutation) ProductID() (r uuid.UUID, exists bool) {
	v := m.product
	if v == nil {
		return
	}
	return *v, true
}

// OldProductID returns the old "product_id" field's value of the UserLog entity.
// If the UserLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserLogMutation) OldProductID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProductID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProductID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProductID: %w", err)
	}
	return oldValue.ProductID, nil
}

// ResetProductID resets all changes to the "product_id" field.
func (m *UserLogMutation) ResetProductID() {
	m.product = nil
}

// ClearProduct clears the "product" edge to the Product entity.
func (m *UserLogMutation) ClearProduct() {
	m.clearedproduct = true
	m.clearedFields[userlog.FieldProductID] = struct{}{}
}

// ProductCleared reports if the "product" edge to the Product entity was cleared.
func (m *UserLogMutation) ProductCleared() bool {
	return m.clearedproduct
}

// ProductIDs returns the "product" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ProductID instead. It exists only for internal usage by the builders.
func (m *UserLogMutation) ProductIDs() (ids []uuid.UUID) {
	if id := m.product; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetProduct resets all changes to the "product" edge.
func (m *UserLogMutation) ResetProduct() {
	m.product = nil
	m.clearedproduct = false
}

// Where appends a list predicates to the UserLogMutation builder.
func (m *UserLogMutation) Where(ps ...predicate.UserLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.UserLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (UserLog).
func (m *UserLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserLogMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.amount != nil {
		fields = append(fields, userlog.FieldAmount)
	}
	if m.date != nil {
		fields = append(fields, userlog.FieldDate)
	}
	if m.user_id != nil {
		fields = append(fields, userlog.FieldUserID)
	}
	if m.product != nil {
		fields = append(fields, userlog.FieldProductID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case userlog.FieldAmount:
		return m.Amount()
	case userlog.FieldDate:
		return m.Date()
	case userlog.FieldUserID:
		return m.UserID()
	case userlog.FieldProductID:
		return m.ProductID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case userlog.FieldAmount:
		return m.OldAmount(ctx)
	case userlog.FieldDate:
		return m.OldDate(ctx)
	case userlog.FieldUserID:
		return m.OldUserID(ctx)
	case userlog.FieldProductID:
		return m.OldProductID(ctx)
	}
	return nil, fmt.Errorf("unknown UserLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case userlog.FieldAmount:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAmount(v)
		return nil
	case userlog.FieldDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDate(v)
		return nil
	case userlog.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case userlog.FieldProductID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProductID(v)
		return nil
	}
	return fmt.Errorf("unknown UserLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserLogMutation) AddedFields() []string {
	var fields []string
	if m.addamount != nil {
		fields = append(fields, userlog.FieldAmount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserLogMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case userlog.FieldAmount:
		return m.AddedAmount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	case userlog.FieldAmount:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAmount(v)
		return nil
	}
	return fmt.Errorf("unknown UserLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserLogMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(userlog.FieldUserID) {
		fields = append(fields, userlog.FieldUserID)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserLogMutation) ClearField(name string) error {
	switch name {
	case userlog.FieldUserID:
		m.ClearUserID()
		return nil
	}
	return fmt.Errorf("unknown UserLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserLogMutation) ResetField(name string) error {
	switch name {
	case userlog.FieldAmount:
		m.ResetAmount()
		return nil
	case userlog.FieldDate:
		m.ResetDate()
		return nil
	case userlog.FieldUserID:
		m.ResetUserID()
		return nil
	case userlog.FieldProductID:
		m.ResetProductID()
		return nil
	}
	return fmt.Errorf("unknown UserLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.product != nil {
		edges = append(edges, userlog.EdgeProduct)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserLogMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case userlog.EdgeProduct:
		if id := m.product; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedproduct {
		edges = append(edges, userlog.EdgeProduct)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserLogMutation) EdgeCleared(name string) bool {
	switch name {
	case userlog.EdgeProduct:
		return m.clearedproduct
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserLogMutation) ClearEdge(name string) error {
	switch name {
	case userlog.EdgeProduct:
		m.ClearProduct()
		return nil
	}
	return fmt.Errorf("unknown UserLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserLogMutation) ResetEdge(name string) error {
	switch name {
	case userlog.EdgeProduct:
		m.ResetProduct()
		return nil
	}
	return fmt.Errorf("unknown UserLog edge %s", name)
}
