// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"devarminas/kcal-track-api/ent/predicate"
	"devarminas/kcal-track-api/ent/product"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeProduct = "Product"
)

// ProductMutation represents an operation that mutates the Product nodes in the graph.
type ProductMutation struct {
	config
	op               Op
	typ              string
	id               *uuid.UUID
	barcode          *string
	name             *string
	brand            *string
	calories         *float64
	addcalories      *float64
	protein          *float64
	addprotein       *float64
	fat              *float64
	addfat           *float64
	saturated_fat    *float64
	addsaturated_fat *float64
	carbohydrates    *float64
	addcarbohydrates *float64
	fiber            *float64
	addfiber         *float64
	sugars           *float64
	addsugars        *float64
	sodium           *float64
	addsodium        *float64
	created_by       *string
	clearedFields    map[string]struct{}
	done             bool
	oldValue         func(context.Context) (*Product, error)
	predicates       []predicate.Product
}

var _ ent.Mutation = (*ProductMutation)(nil)

// productOption allows management of the mutation configuration using functional options.
type productOption func(*ProductMutation)

// newProductMutation creates new mutation for the Product entity.
func newProductMutation(c config, op Op, opts ...productOption) *ProductMutation {
	m := &ProductMutation{
		config:        c,
		op:            op,
		typ:           TypeProduct,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withProductID sets the ID field of the mutation.
func withProductID(id uuid.UUID) productOption {
	return func(m *ProductMutation) {
		var (
			err   error
			once  sync.Once
			value *Product
		)
		m.oldValue = func(ctx context.Context) (*Product, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Product.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withProduct sets the old Product of the mutation.
func withProduct(node *Product) productOption {
	return func(m *ProductMutation) {
		m.oldValue = func(context.Context) (*Product, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ProductMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ProductMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Product entities.
func (m *ProductMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ProductMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ProductMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Product.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetBarcode sets the "barcode" field.
func (m *ProductMutation) SetBarcode(s string) {
	m.barcode = &s
}

// Barcode returns the value of the "barcode" field in the mutation.
func (m *ProductMutation) Barcode() (r string, exists bool) {
	v := m.barcode
	if v == nil {
		return
	}
	return *v, true
}

// OldBarcode returns the old "barcode" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldBarcode(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBarcode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBarcode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBarcode: %w", err)
	}
	return oldValue.Barcode, nil
}

// ClearBarcode clears the value of the "barcode" field.
func (m *ProductMutation) ClearBarcode() {
	m.barcode = nil
	m.clearedFields[product.FieldBarcode] = struct{}{}
}

// BarcodeCleared returns if the "barcode" field was cleared in this mutation.
func (m *ProductMutation) BarcodeCleared() bool {
	_, ok := m.clearedFields[product.FieldBarcode]
	return ok
}

// ResetBarcode resets all changes to the "barcode" field.
func (m *ProductMutation) ResetBarcode() {
	m.barcode = nil
	delete(m.clearedFields, product.FieldBarcode)
}

// SetName sets the "name" field.
func (m *ProductMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ProductMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ProductMutation) ResetName() {
	m.name = nil
}

// SetBrand sets the "brand" field.
func (m *ProductMutation) SetBrand(s string) {
	m.brand = &s
}

// Brand returns the value of the "brand" field in the mutation.
func (m *ProductMutation) Brand() (r string, exists bool) {
	v := m.brand
	if v == nil {
		return
	}
	return *v, true
}

// OldBrand returns the old "brand" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldBrand(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBrand is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBrand requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBrand: %w", err)
	}
	return oldValue.Brand, nil
}

// ClearBrand clears the value of the "brand" field.
func (m *ProductMutation) ClearBrand() {
	m.brand = nil
	m.clearedFields[product.FieldBrand] = struct{}{}
}

// BrandCleared returns if the "brand" field was cleared in this mutation.
func (m *ProductMutation) BrandCleared() bool {
	_, ok := m.clearedFields[product.FieldBrand]
	return ok
}

// ResetBrand resets all changes to the "brand" field.
func (m *ProductMutation) ResetBrand() {
	m.brand = nil
	delete(m.clearedFields, product.FieldBrand)
}

// SetCalories sets the "calories" field.
func (m *ProductMutation) SetCalories(f float64) {
	m.calories = &f
	m.addcalories = nil
}

// Calories returns the value of the "calories" field in the mutation.
func (m *ProductMutation) Calories() (r float64, exists bool) {
	v := m.calories
	if v == nil {
		return
	}
	return *v, true
}

// OldCalories returns the old "calories" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldCalories(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCalories is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCalories requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCalories: %w", err)
	}
	return oldValue.Calories, nil
}

// AddCalories adds f to the "calories" field.
func (m *ProductMutation) AddCalories(f float64) {
	if m.addcalories != nil {
		*m.addcalories += f
	} else {
		m.addcalories = &f
	}
}

// AddedCalories returns the value that was added to the "calories" field in this mutation.
func (m *ProductMutation) AddedCalories() (r float64, exists bool) {
	v := m.addcalories
	if v == nil {
		return
	}
	return *v, true
}

// ResetCalories resets all changes to the "calories" field.
func (m *ProductMutation) ResetCalories() {
	m.calories = nil
	m.addcalories = nil
}

// SetProtein sets the "protein" field.
func (m *ProductMutation) SetProtein(f float64) {
	m.protein = &f
	m.addprotein = nil
}

// Protein returns the value of the "protein" field in the mutation.
func (m *ProductMutation) Protein() (r float64, exists bool) {
	v := m.protein
	if v == nil {
		return
	}
	return *v, true
}

// OldProtein returns the old "protein" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldProtein(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProtein is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProtein requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProtein: %w", err)
	}
	return oldValue.Protein, nil
}

// AddProtein adds f to the "protein" field.
func (m *ProductMutation) AddProtein(f float64) {
	if m.addprotein != nil {
		*m.addprotein += f
	} else {
		m.addprotein = &f
	}
}

// AddedProtein returns the value that was added to the "protein" field in this mutation.
func (m *ProductMutation) AddedProtein() (r float64, exists bool) {
	v := m.addprotein
	if v == nil {
		return
	}
	return *v, true
}

// ResetProtein resets all changes to the "protein" field.
func (m *ProductMutation) ResetProtein() {
	m.protein = nil
	m.addprotein = nil
}

// SetFat sets the "fat" field.
func (m *ProductMutation) SetFat(f float64) {
	m.fat = &f
	m.addfat = nil
}

// Fat returns the value of the "fat" field in the mutation.
func (m *ProductMutation) Fat() (r float64, exists bool) {
	v := m.fat
	if v == nil {
		return
	}
	return *v, true
}

// OldFat returns the old "fat" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldFat(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFat is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFat requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFat: %w", err)
	}
	return oldValue.Fat, nil
}

// AddFat adds f to the "fat" field.
func (m *ProductMutation) AddFat(f float64) {
	if m.addfat != nil {
		*m.addfat += f
	} else {
		m.addfat = &f
	}
}

// AddedFat returns the value that was added to the "fat" field in this mutation.
func (m *ProductMutation) AddedFat() (r float64, exists bool) {
	v := m.addfat
	if v == nil {
		return
	}
	return *v, true
}

// ResetFat resets all changes to the "fat" field.
func (m *ProductMutation) ResetFat() {
	m.fat = nil
	m.addfat = nil
}

// SetSaturatedFat sets the "saturated_fat" field.
func (m *ProductMutation) SetSaturatedFat(f float64) {
	m.saturated_fat = &f
	m.addsaturated_fat = nil
}

// SaturatedFat returns the value of the "saturated_fat" field in the mutation.
func (m *ProductMutation) SaturatedFat() (r float64, exists bool) {
	v := m.saturated_fat
	if v == nil {
		return
	}
	return *v, true
}

// OldSaturatedFat returns the old "saturated_fat" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldSaturatedFat(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSaturatedFat is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSaturatedFat requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSaturatedFat: %w", err)
	}
	return oldValue.SaturatedFat, nil
}

// AddSaturatedFat adds f to the "saturated_fat" field.
func (m *ProductMutation) AddSaturatedFat(f float64) {
	if m.addsaturated_fat != nil {
		*m.addsaturated_fat += f
	} else {
		m.addsaturated_fat = &f
	}
}

// AddedSaturatedFat returns the value that was added to the "saturated_fat" field in this mutation.
func (m *ProductMutation) AddedSaturatedFat() (r float64, exists bool) {
	v := m.addsaturated_fat
	if v == nil {
		return
	}
	return *v, true
}

// ResetSaturatedFat resets all changes to the "saturated_fat" field.
func (m *ProductMutation) ResetSaturatedFat() {
	m.saturated_fat = nil
	m.addsaturated_fat = nil
}

// SetCarbohydrates sets the "carbohydrates" field.
func (m *ProductMutation) SetCarbohydrates(f float64) {
	m.carbohydrates = &f
	m.addcarbohydrates = nil
}

// Carbohydrates returns the value of the "carbohydrates" field in the mutation.
func (m *ProductMutation) Carbohydrates() (r float64, exists bool) {
	v := m.carbohydrates
	if v == nil {
		return
	}
	return *v, true
}

// OldCarbohydrates returns the old "carbohydrates" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldCarbohydrates(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCarbohydrates is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCarbohydrates requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCarbohydrates: %w", err)
	}
	return oldValue.Carbohydrates, nil
}

// AddCarbohydrates adds f to the "carbohydrates" field.
func (m *ProductMutation) AddCarbohydrates(f float64) {
	if m.addcarbohydrates != nil {
		*m.addcarbohydrates += f
	} else {
		m.addcarbohydrates = &f
	}
}

// AddedCarbohydrates returns the value that was added to the "carbohydrates" field in this mutation.
func (m *ProductMutation) AddedCarbohydrates() (r float64, exists bool) {
	v := m.addcarbohydrates
	if v == nil {
		return
	}
	return *v, true
}

// ResetCarbohydrates resets all changes to the "carbohydrates" field.
func (m *ProductMutation) ResetCarbohydrates() {
	m.carbohydrates = nil
	m.addcarbohydrates = nil
}

// SetFiber sets the "fiber" field.
func (m *ProductMutation) SetFiber(f float64) {
	m.fiber = &f
	m.addfiber = nil
}

// Fiber returns the value of the "fiber" field in the mutation.
func (m *ProductMutation) Fiber() (r float64, exists bool) {
	v := m.fiber
	if v == nil {
		return
	}
	return *v, true
}

// OldFiber returns the old "fiber" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldFiber(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFiber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFiber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFiber: %w", err)
	}
	return oldValue.Fiber, nil
}

// AddFiber adds f to the "fiber" field.
func (m *ProductMutation) AddFiber(f float64) {
	if m.addfiber != nil {
		*m.addfiber += f
	} else {
		m.addfiber = &f
	}
}

// AddedFiber returns the value that was added to the "fiber" field in this mutation.
func (m *ProductMutation) AddedFiber() (r float64, exists bool) {
	v := m.addfiber
	if v == nil {
		return
	}
	return *v, true
}

// ResetFiber resets all changes to the "fiber" field.
func (m *ProductMutation) ResetFiber() {
	m.fiber = nil
	m.addfiber = nil
}

// SetSugars sets the "sugars" field.
func (m *ProductMutation) SetSugars(f float64) {
	m.sugars = &f
	m.addsugars = nil
}

// Sugars returns the value of the "sugars" field in the mutation.
func (m *ProductMutation) Sugars() (r float64, exists bool) {
	v := m.sugars
	if v == nil {
		return
	}
	return *v, true
}

// OldSugars returns the old "sugars" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldSugars(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSugars is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSugars requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSugars: %w", err)
	}
	return oldValue.Sugars, nil
}

// AddSugars adds f to the "sugars" field.
func (m *ProductMutation) AddSugars(f float64) {
	if m.addsugars != nil {
		*m.addsugars += f
	} else {
		m.addsugars = &f
	}
}

// AddedSugars returns the value that was added to the "sugars" field in this mutation.
func (m *ProductMutation) AddedSugars() (r float64, exists bool) {
	v := m.addsugars
	if v == nil {
		return
	}
	return *v, true
}

// ResetSugars resets all changes to the "sugars" field.
func (m *ProductMutation) ResetSugars() {
	m.sugars = nil
	m.addsugars = nil
}

// SetSodium sets the "sodium" field.
func (m *ProductMutation) SetSodium(f float64) {
	m.sodium = &f
	m.addsodium = nil
}

// Sodium returns the value of the "sodium" field in the mutation.
func (m *ProductMutation) Sodium() (r float64, exists bool) {
	v := m.sodium
	if v == nil {
		return
	}
	return *v, true
}

// OldSodium returns the old "sodium" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldSodium(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSodium is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSodium requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSodium: %w", err)
	}
	return oldValue.Sodium, nil
}

// AddSodium adds f to the "sodium" field.
func (m *ProductMutation) AddSodium(f float64) {
	if m.addsodium != nil {
		*m.addsodium += f
	} else {
		m.addsodium = &f
	}
}

// AddedSodium returns the value that was added to the "sodium" field in this mutation.
func (m *ProductMutation) AddedSodium() (r float64, exists bool) {
	v := m.addsodium
	if v == nil {
		return
	}
	return *v, true
}

// ResetSodium resets all changes to the "sodium" field.
func (m *ProductMutation) ResetSodium() {
	m.sodium = nil
	m.addsodium = nil
}

// SetCreatedBy sets the "created_by" field.
func (m *ProductMutation) SetCreatedBy(s string) {
	m.created_by = &s
}

// CreatedBy returns the value of the "created_by" field in the mutation.
func (m *ProductMutation) CreatedBy() (r string, exists bool) {
	v := m.created_by
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedBy returns the old "created_by" field's value of the Product entity.
// If the Product object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldCreatedBy(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedBy: %w", err)
	}
	return oldValue.CreatedBy, nil
}

// ClearCreatedBy clears the value of the "created_by" field.
func (m *ProductMutation) ClearCreatedBy() {
	m.created_by = nil
	m.clearedFields[product.FieldCreatedBy] = struct{}{}
}

// CreatedByCleared returns if the "created_by" field was cleared in this mutation.
func (m *ProductMutation) CreatedByCleared() bool {
	_, ok := m.clearedFields[product.FieldCreatedBy]
	return ok
}

// ResetCreatedBy resets all changes to the "created_by" field.
func (m *ProductMutation) ResetCreatedBy() {
	m.created_by = nil
	delete(m.clearedFields, product.FieldCreatedBy)
}

// Where appends a list predicates to the ProductMutation builder.
func (m *ProductMutation) Where(ps ...predicate.Product) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ProductMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ProductMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Product, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ProductMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ProductMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Product).
func (m *ProductMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ProductMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.barcode != nil {
		fields = append(fields, product.FieldBarcode)
	}
	if m.name != nil {
		fields = append(fields, product.FieldName)
	}
	if m.brand != nil {
		fields = append(fields, product.FieldBrand)
	}
	if m.calories != nil {
		fields = append(fields, product.FieldCalories)
	}
	if m.protein != nil {
		fields = append(fields, product.FieldProtein)
	}
	if m.fat != nil {
		fields = append(fields, product.FieldFat)
	}
	if m.saturated_fat != nil {
		fields = append(fields, product.FieldSaturatedFat)
	}
	if m.carbohydrates != nil {
		fields = append(fields, product.FieldCarbohydrates)
	}
	if m.fiber != nil {
		fields = append(fields, product.FieldFiber)
	}
	if m.sugars != nil {
		fields = append(fields, product.FieldSugars)
	}
	if m.sodium != nil {
		fields = append(fields, product.FieldSodium)
	}
	if m.created_by != nil {
		fields = append(fields, product.FieldCreatedBy)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ProductMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case product.FieldBarcode:
		return m.Barcode()
	case product.FieldName:
		return m.Name()
	case product.FieldBrand:
		return m.Brand()
	case product.FieldCalories:
		return m.Calories()
	case product.FieldProtein:
		return m.Protein()
	case product.FieldFat:
		return m.Fat()
	case product.FieldSaturatedFat:
		return m.SaturatedFat()
	case product.FieldCarbohydrates:
		return m.Carbohydrates()
	case product.FieldFiber:
		return m.Fiber()
	case product.FieldSugars:
		return m.Sugars()
	case product.FieldSodium:
		return m.Sodium()
	case product.FieldCreatedBy:
		return m.CreatedBy()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ProductMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case product.FieldBarcode:
		return m.OldBarcode(ctx)
	case product.FieldName:
		return m.OldName(ctx)
	case product.FieldBrand:
		return m.OldBrand(ctx)
	case product.FieldCalories:
		return m.OldCalories(ctx)
	case product.FieldProtein:
		return m.OldProtein(ctx)
	case product.FieldFat:
		return m.OldFat(ctx)
	case product.FieldSaturatedFat:
		return m.OldSaturatedFat(ctx)
	case product.FieldCarbohydrates:
		return m.OldCarbohydrates(ctx)
	case product.FieldFiber:
		return m.OldFiber(ctx)
	case product.FieldSugars:
		return m.OldSugars(ctx)
	case product.FieldSodium:
		return m.OldSodium(ctx)
	case product.FieldCreatedBy:
		return m.OldCreatedBy(ctx)
	}
	return nil, fmt.Errorf("unknown Product field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProductMutation) SetField(name string, value ent.Value) error {
	switch name {
	case product.FieldBarcode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBarcode(v)
		return nil
	case product.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case product.FieldBrand:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBrand(v)
		return nil
	case product.FieldCalories:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCalories(v)
		return nil
	case product.FieldProtein:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProtein(v)
		return nil
	case product.FieldFat:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFat(v)
		return nil
	case product.FieldSaturatedFat:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSaturatedFat(v)
		return nil
	case product.FieldCarbohydrates:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCarbohydrates(v)
		return nil
	case product.FieldFiber:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFiber(v)
		return nil
	case product.FieldSugars:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSugars(v)
		return nil
	case product.FieldSodium:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSodium(v)
		return nil
	case product.FieldCreatedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedBy(v)
		return nil
	}
	return fmt.Errorf("unknown Product field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ProductMutation) AddedFields() []string {
	var fields []string
	if m.addcalories != nil {
		fields = append(fields, product.FieldCalories)
	}
	if m.addprotein != nil {
		fields = append(fields, product.FieldProtein)
	}
	if m.addfat != nil {
		fields = append(fields, product.FieldFat)
	}
	if m.addsaturated_fat != nil {
		fields = append(fields, product.FieldSaturatedFat)
	}
	if m.addcarbohydrates != nil {
		fields = append(fields, product.FieldCarbohydrates)
	}
	if m.addfiber != nil {
		fields = append(fields, product.FieldFiber)
	}
	if m.addsugars != nil {
		fields = append(fields, product.FieldSugars)
	}
	if m.addsodium != nil {
		fields = append(fields, product.FieldSodium)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ProductMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case product.FieldCalories:
		return m.AddedCalories()
	case product.FieldProtein:
		return m.AddedProtein()
	case product.FieldFat:
		return m.AddedFat()
	case product.FieldSaturatedFat:
		return m.AddedSaturatedFat()
	case product.FieldCarbohydrates:
		return m.AddedCarbohydrates()
	case product.FieldFiber:
		return m.AddedFiber()
	case product.FieldSugars:
		return m.AddedSugars()
	case product.FieldSodium:
		return m.AddedSodium()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProductMutation) AddField(name string, value ent.Value) error {
	switch name {
	case product.FieldCalories:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCalories(v)
		return nil
	case product.FieldProtein:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddProtein(v)
		return nil
	case product.FieldFat:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddFat(v)
		return nil
	case product.FieldSaturatedFat:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSaturatedFat(v)
		return nil
	case product.FieldCarbohydrates:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCarbohydrates(v)
		return nil
	case product.FieldFiber:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddFiber(v)
		return nil
	case product.FieldSugars:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSugars(v)
		return nil
	case product.FieldSodium:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSodium(v)
		return nil
	}
	return fmt.Errorf("unknown Product numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ProductMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(product.FieldBarcode) {
		fields = append(fields, product.FieldBarcode)
	}
	if m.FieldCleared(product.FieldBrand) {
		fields = append(fields, product.FieldBrand)
	}
	if m.FieldCleared(product.FieldCreatedBy) {
		fields = append(fields, product.FieldCreatedBy)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ProductMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ProductMutation) ClearField(name string) error {
	switch name {
	case product.FieldBarcode:
		m.ClearBarcode()
		return nil
	case product.FieldBrand:
		m.ClearBrand()
		return nil
	case product.FieldCreatedBy:
		m.ClearCreatedBy()
		return nil
	}
	return fmt.Errorf("unknown Product nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ProductMutation) ResetField(name string) error {
	switch name {
	case product.FieldBarcode:
		m.ResetBarcode()
		return nil
	case product.FieldName:
		m.ResetName()
		return nil
	case product.FieldBrand:
		m.ResetBrand()
		return nil
	case product.FieldCalories:
		m.ResetCalories()
		return nil
	case product.FieldProtein:
		m.ResetProtein()
		return nil
	case product.FieldFat:
		m.ResetFat()
		return nil
	case product.FieldSaturatedFat:
		m.ResetSaturatedFat()
		return nil
	case product.FieldCarbohydrates:
		m.ResetCarbohydrates()
		return nil
	case product.FieldFiber:
		m.ResetFiber()
		return nil
	case product.FieldSugars:
		m.ResetSugars()
		return nil
	case product.FieldSodium:
		m.ResetSodium()
		return nil
	case product.FieldCreatedBy:
		m.ResetCreatedBy()
		return nil
	}
	return fmt.Errorf("unknown Product field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ProductMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ProductMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ProductMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ProductMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ProductMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ProductMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ProductMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Product unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ProductMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Product edge %s", name)
}
