// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"devarminas/kcal-track-api/ent/product"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProductCreate is the builder for creating a Product entity.
type ProductCreate struct {
	config
	mutation *ProductMutation
	hooks    []Hook
}

// SetBarcode sets the "barcode" field.
func (_c *ProductCreate) SetBarcode(v string) *ProductCreate {
	_c.mutation.SetBarcode(v)
	return _c
}

// SetNillableBarcode sets the "barcode" field if the given value is not nil.
func (_c *ProductCreate) SetNillableBarcode(v *string) *ProductCreate {
	if v != nil {
		_c.SetBarcode(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ProductCreate) SetName(v string) *ProductCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetBrand sets the "brand" field.
func (_c *ProductCreate) SetBrand(v string) *ProductCreate {
	_c.mutation.SetBrand(v)
	return _c
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (_c *ProductCreate) SetNillableBrand(v *string) *ProductCreate {
	if v != nil {
		_c.SetBrand(*v)
	}
	return _c
}

// SetCalories sets the "calories" field.
func (_c *ProductCreate) SetCalories(v float64) *ProductCreate {
	_c.mutation.SetCalories(v)
	return _c
}

// SetProtein sets the "protein" field.
func (_c *ProductCreate) SetProtein(v float64) *ProductCreate {
	_c.mutation.SetProtein(v)
	return _c
}

// SetFat sets the "fat" field.
func (_c *ProductCreate) SetFat(v float64) *ProductCreate {
	_c.mutation.SetFat(v)
	return _c
}

// SetSaturatedFat sets the "saturated_fat" field.
func (_c *ProductCreate) SetSaturatedFat(v float64) *ProductCreate {
	_c.mutation.SetSaturatedFat(v)
	return _c
}

// SetCarbohydrates sets the "carbohydrates" field.
func (_c *ProductCreate) SetCarbohydrates(v float64) *ProductCreate {
	_c.mutation.SetCarbohydrates(v)
	return _c
}

// SetFiber sets the "fiber" field.
func (_c *ProductCreate) SetFiber(v float64) *ProductCreate {
	_c.mutation.SetFiber(v)
	return _c
}

// SetSugars sets the "sugars" field.
func (_c *ProductCreate) SetSugars(v float64) *ProductCreate {
	_c.mutation.SetSugars(v)
	return _c
}

// SetSodium sets the "sodium" field.
func (_c *ProductCreate) SetSodium(v float64) *ProductCreate {
	_c.mutation.SetSodium(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ProductCreate) SetCreatedBy(v string) *ProductCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ProductCreate) SetNillableCreatedBy(v *string) *ProductCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProductCreate) SetID(v uuid.UUID) *ProductCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProductCreate) SetNillableID(v *uuid.UUID) *ProductCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ProductMutation object of the builder.
func (_c *ProductCreate) Mutation() *ProductMutation {
	return _c.mutation
}

// Save creates the Product in the database.
func (_c *ProductCreate) Save(ctx context.Context) (*Product, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProductCreate) SaveX(ctx context.Context) *Product {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProductCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProductCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProductCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := product.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProductCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Product.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := product.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Product.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Calories(); !ok {
		return &ValidationError{Name: "calories", err: errors.New(`ent: missing required field "Product.calories"`)}
	}
	if v, ok := _c.mutation.Calories(); ok {
		if err := product.CaloriesValidator(v); err != nil {
			return &ValidationError{Name: "calories", err: fmt.Errorf(`ent: validator failed for field "Product.calories": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Protein(); !ok {
		return &ValidationError{Name: "protein", err: errors.New(`ent: missing required field "Product.protein"`)}
	}
	if v, ok := _c.mutation.Protein(); ok {
		if err := product.ProteinValidator(v); err != nil {
			return &ValidationError{Name: "protein", err: fmt.Errorf(`ent: validator failed for field "Product.protein": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Fat(); !ok {
		return &ValidationError{Name: "fat", err: errors.New(`ent: missing required field "Product.fat"`)}
	}
	if v, ok := _c.mutation.Fat(); ok {
		if err := product.FatValidator(v); err != nil {
			return &ValidationError{Name: "fat", err: fmt.Errorf(`ent: validator failed for field "Product.fat": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SaturatedFat(); !ok {
		return &ValidationError{Name: "saturated_fat", err: errors.New(`ent: missing required field "Product.saturated_fat"`)}
	}
	if v, ok := _c.mutation.SaturatedFat(); ok {
		if err := product.SaturatedFatValidator(v); err != nil {
			return &ValidationError{Name: "saturated_fat", err: fmt.Errorf(`ent: validator failed for field "Product.saturated_fat": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Carbohydrates(); !ok {
		return &ValidationError{Name: "carbohydrates", err: errors.New(`ent: missing required field "Product.carbohydrates"`)}
	}
	if v, ok := _c.mutation.Carbohydrates(); ok {
		if err := product.CarbohydratesValidator(v); err != nil {
			return &ValidationError{Name: "carbohydrates", err: fmt.Errorf(`ent: validator failed for field "Product.carbohydrates": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Fiber(); !ok {
		return &ValidationError{Name: "fiber", err: errors.New(`ent: missing required field "Product.fiber"`)}
	}
	if v, ok := _c.mutation.Fiber(); ok {
		if err := product.FiberValidator(v); err != nil {
			return &ValidationError{Name: "fiber", err: fmt.Errorf(`ent: validator failed for field "Product.fiber": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sugars(); !ok {
		return &ValidationError{Name: "sugars", err: errors.New(`ent: missing required field "Product.sugars"`)}
	}
	if v, ok := _c.mutation.Sugars(); ok {
		if err := product.SugarsValidator(v); err != nil {
			return &ValidationError{Name: "sugars", err: fmt.Errorf(`ent: validator failed for field "Product.sugars": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sodium(); !ok {
		return &ValidationError{Name: "sodium", err: errors.New(`ent: missing required field "Product.sodium"`)}
	}
	if v, ok := _c.mutation.Sodium(); ok {
		if err := product.SodiumValidator(v); err != nil {
			return &ValidationError{Name: "sodium", err: fmt.Errorf(`ent: validator failed for field "Product.sodium": %w`, err)}
		}
	}
	return nil
}

func (_c *ProductCreate) sqlSave(ctx context.Context) (*Product, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProductCreate) createSpec() (*Product, *sqlgraph.CreateSpec) {
	var (
		_node = &Product{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(product.Table, sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Barcode(); ok {
		_spec.SetField(product.FieldBarcode, field.TypeString, value)
		_node.Barcode = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Brand(); ok {
		_spec.SetField(product.FieldBrand, field.TypeString, value)
		_node.Brand = &value
	}
	if value, ok := _c.mutation.Calories(); ok {
		_spec.SetField(product.FieldCalories, field.TypeFloat64, value)
		_node.Calories = value
	}
	if value, ok := _c.mutation.Protein(); ok {
		_spec.SetField(product.FieldProtein, field.TypeFloat64, value)
		_node.Protein = value
	}
	if value, ok := _c.mutation.Fat(); ok {
		_spec.SetField(product.FieldFat, field.TypeFloat64, value)
		_node.Fat = value
	}
	if value, ok := _c.mutation.SaturatedFat(); ok {
		_spec.SetField(product.FieldSaturatedFat, field.TypeFloat64, value)
		_node.SaturatedFat = value
	}
	if value, ok := _c.mutation.Carbohydrates(); ok {
		_spec.SetField(product.FieldCarbohydrates, field.TypeFloat64, value)
		_node.Carbohydrates = value
	}
	if value, ok := _c.mutation.Fiber(); ok {
		_spec.SetField(product.FieldFiber, field.TypeFloat64, value)
		_node.Fiber = value
	}
	if value, ok := _c.mutation.Sugars(); ok {
		_spec.SetField(product.FieldSugars, field.TypeFloat64, value)
		_node.Sugars = value
	}
	if value, ok := _c.mutation.Sodium(); ok {
		_spec.SetField(product.FieldSodium, field.TypeFloat64, value)
		_node.Sodium = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(product.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = &value
	}
	return _node, _spec
}

// ProductCreateBulk is the builder for creating many Product entities in bulk.
type ProductCreateBulk struct {
	config
	err      error
	builders []*ProductCreate
}

// Save creates the Product entities in the database.
func (_c *ProductCreateBulk) Save(ctx context.Context) ([]*Product, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Product, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProductCreateBulk) SaveX(ctx context.Context) []*Product {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProductCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProductCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
