// Code generated by ent, DO NOT EDIT.

package ent

import (
	"devarminas/kcal-track-api/ent/product"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Product is the model entity for the Product schema.
type Product struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Barcode holds the value of the "barcode" field.
	Barcode *string `json:"barcode,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Brand holds the value of the "brand" field.
	Brand *string `json:"brand,omitempty"`
	// Calories holds the value of the "calories" field.
	Calories float64 `json:"calories,omitempty"`
	// Protein holds the value of the "protein" field.
	Protein float64 `json:"protein,omitempty"`
	// Fat holds the value of the "fat" field.
	Fat float64 `json:"fat,omitempty"`
	// SaturatedFat holds the value of the "saturated_fat" field.
	SaturatedFat float64 `json:"saturated_fat,omitempty"`
	// Carbohydrates holds the value of the "carbohydrates" field.
	Carbohydrates float64 `json:"carbohydrates,omitempty"`
	// Fiber holds the value of the "fiber" field.
	Fiber float64 `json:"fiber,omitempty"`
	// Sugars holds the value of the "sugars" field.
	Sugars float64 `json:"sugars,omitempty"`
	// Sodium holds the value of the "sodium" field.
	Sodium float64 `json:"sodium,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID *string `json:"owner_id,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID *uuid.UUID `json:"parent_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProductQuery when eager-loading is set.
	Edges        ProductEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProductEdges holds the relations/edges for other nodes in the graph.
type ProductEdges struct {
	// OriginalSource holds the value of the original_source edge.
	OriginalSource *Product `json:"original_source,omitempty"`
	// Forks holds the value of the forks edge.
	Forks []*Product `json:"forks,omitempty"`
	// UserLogs holds the value of the user_logs edge.
	UserLogs []*UserLog `json:"user_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// OriginalSourceOrErr returns the OriginalSource value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProductEdges) OriginalSourceOrErr() (*Product, error) {
	if e.OriginalSource != nil {
		return e.OriginalSource, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "original_source"}
}

// ForksOrErr returns the Forks value or an error if the edge
// was not loaded in eager-loading.
func (e ProductEdges) ForksOrErr() ([]*Product, error) {
	if e.loadedTypes[1] {
		return e.Forks, nil
	}
	return nil, &NotLoadedError{edge: "forks"}
}

// UserLogsOrErr returns the UserLogs value or an error if the edge
// was not loaded in eager-loading.
func (e ProductEdges) UserLogsOrErr() ([]*UserLog, error) {
	if e.loadedTypes[2] {
		return e.UserLogs, nil
	}
	return nil, &NotLoadedError{edge: "user_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Product) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case product.FieldParentID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case product.FieldCalories, product.FieldProtein, product.FieldFat, product.FieldSaturatedFat, product.FieldCarbohydrates, product.FieldFiber, product.FieldSugars, product.FieldSodium:
			values[i] = new(sql.NullFloat64)
		case product.FieldBarcode, product.FieldName, product.FieldBrand, product.FieldOwnerID:
			values[i] = new(sql.NullString)
		case product.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Product fields.
func (_m *Product) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case product.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case product.FieldBarcode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field barcode", values[i])
			} else if value.Valid {
				_m.Barcode = new(string)
				*_m.Barcode = value.String
			}
		case product.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case product.FieldBrand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field brand", values[i])
			} else if value.Valid {
				_m.Brand = new(string)
				*_m.Brand = value.String
			}
		case product.FieldCalories:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field calories", values[i])
			} else if value.Valid {
				_m.Calories = value.Float64
			}
		case product.FieldProtein:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field protein", values[i])
			} else if value.Valid {
				_m.Protein = value.Float64
			}
		case product.FieldFat:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fat", values[i])
			} else if value.Valid {
				_m.Fat = value.Float64
			}
		case product.FieldSaturatedFat:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field saturated_fat", values[i])
			} else if value.Valid {
				_m.SaturatedFat = value.Float64
			}
		case product.FieldCarbohydrates:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field carbohydrates", values[i])
			} else if value.Valid {
				_m.Carbohydrates = value.Float64
			}
		case product.FieldFiber:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fiber", values[i])
			} else if value.Valid {
				_m.Fiber = value.Float64
			}
		case product.FieldSugars:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field sugars", values[i])
			} else if value.Valid {
				_m.Sugars = value.Float64
			}
		case product.FieldSodium:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field sodium", values[i])
			} else if value.Valid {
				_m.Sodium = value.Float64
			}
		case product.FieldOwnerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				_m.OwnerID = new(string)
				*_m.OwnerID = value.String
			}
		case product.FieldParentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = new(uuid.UUID)
				*_m.ParentID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Product.
// This includes values selected through modifiers, order, etc.
func (_m *Product) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOriginalSource queries the "original_source" edge of the Product entity.
func (_m *Product) QueryOriginalSource() *ProductQuery {
	return NewProductClient(_m.config).QueryOriginalSource(_m)
}

// QueryForks queries the "forks" edge of the Product entity.
func (_m *Product) QueryForks() *ProductQuery {
	return NewProductClient(_m.config).QueryForks(_m)
}

// QueryUserLogs queries the "user_logs" edge of the Product entity.
func (_m *Product) QueryUserLogs() *UserLogQuery {
	return NewProductClient(_m.config).QueryUserLogs(_m)
}

// Update returns a builder for updating this Product.
// Note that you need to call Product.Unwrap() before calling this method if this Product
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Product) Update() *ProductUpdateOne {
	return NewProductClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Product entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Product) Unwrap() *Product {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Product is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Product) String() string {
	var builder strings.Builder
	builder.WriteString("Product(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.Barcode; v != nil {
		builder.WriteString("barcode=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Brand; v != nil {
		builder.WriteString("brand=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("calories=")
	builder.WriteString(fmt.Sprintf("%v", _m.Calories))
	builder.WriteString(", ")
	builder.WriteString("protein=")
	builder.WriteString(fmt.Sprintf("%v", _m.Protein))
	builder.WriteString(", ")
	builder.WriteString("fat=")
	builder.WriteString(fmt.Sprintf("%v", _m.Fat))
	builder.WriteString(", ")
	builder.WriteString("saturated_fat=")
	builder.WriteString(fmt.Sprintf("%v", _m.SaturatedFat))
	builder.WriteString(", ")
	builder.WriteString("carbohydrates=")
	builder.WriteString(fmt.Sprintf("%v", _m.Carbohydrates))
	builder.WriteString(", ")
	builder.WriteString("fiber=")
	builder.WriteString(fmt.Sprintf("%v", _m.Fiber))
	builder.WriteString(", ")
	builder.WriteString("sugars=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sugars))
	builder.WriteString(", ")
	builder.WriteString("sodium=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sodium))
	builder.WriteString(", ")
	if v := _m.OwnerID; v != nil {
		builder.WriteString("owner_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Products is a parsable slice of Product.
type Products []*Product
