// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"devarminas/kcal-track-api/ent/predicate"
	"devarminas/kcal-track-api/ent/product"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks    []Hook
	mutation *ProductMutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (_u *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBarcode sets the "barcode" field.
func (_u *ProductUpdate) SetBarcode(v string) *ProductUpdate {
	_u.mutation.SetBarcode(v)
	return _u
}

// SetNillableBarcode sets the "barcode" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableBarcode(v *string) *ProductUpdate {
	if v != nil {
		_u.SetBarcode(*v)
	}
	return _u
}

// ClearBarcode clears the value of the "barcode" field.
func (_u *ProductUpdate) ClearBarcode() *ProductUpdate {
	_u.mutation.ClearBarcode()
	return _u
}

// SetName sets the "name" field.
func (_u *ProductUpdate) SetName(v string) *ProductUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableName(v *string) *ProductUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBrand sets the "brand" field.
func (_u *ProductUpdate) SetBrand(v string) *ProductUpdate {
	_u.mutation.SetBrand(v)
	return _u
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableBrand(v *string) *ProductUpdate {
	if v != nil {
		_u.SetBrand(*v)
	}
	return _u
}

// ClearBrand clears the value of the "brand" field.
func (_u *ProductUpdate) ClearBrand() *ProductUpdate {
	_u.mutation.ClearBrand()
	return _u
}

// SetCalories sets the "calories" field.
func (_u *ProductUpdate) SetCalories(v float64) *ProductUpdate {
	_u.mutation.ResetCalories()
	_u.mutation.SetCalories(v)
	return _u
}

// SetNillableCalories sets the "calories" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableCalories(v *float64) *ProductUpdate {
	if v != nil {
		_u.SetCalories(*v)
	}
	return _u
}

// AddCalories adds value to the "calories" field.
func (_u *ProductUpdate) AddCalories(v float64) *ProductUpdate {
	_u.mutation.AddCalories(v)
	return _u
}

// SetProtein sets the "protein" field.
func (_u *ProductUpdate) SetProtein(v float64) *ProductUpdate {
	_u.mutation.ResetProtein()
	_u.mutation.SetProtein(v)
	return _u
}

// SetNillableProtein sets the "protein" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableProtein(v *float64) *ProductUpdate {
	if v != nil {
		_u.SetProtein(*v)
	}
	return _u
}

// AddProtein adds value to the "protein" field.
func (_u *ProductUpdate) AddProtein(v float64) *ProductUpdate {
	_u.mutation.AddProtein(v)
	return _u
}

// SetFat sets the "fat" field.
func (_u *ProductUpdate) SetFat(v float64) *ProductUpdate {
	_u.mutation.ResetFat()
	_u.mutation.SetFat(v)
	return _u
}

// SetNillableFat sets the "fat" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableFat(v *float64) *ProductUpdate {
	if v != nil {
		_u.SetFat(*v)
	}
	return _u
}

// AddFat adds value to the "fat" field.
func (_u *ProductUpdate) AddFat(v float64) *ProductUpdate {
	_u.mutation.AddFat(v)
	return _u
}

// SetSaturatedFat sets the "saturated_fat" field.
func (_u *ProductUpdate) SetSaturatedFat(v float64) *ProductUpdate {
	_u.mutation.ResetSaturatedFat()
	_u.mutation.SetSaturatedFat(v)
	return _u
}

// SetNillableSaturatedFat sets the "saturated_fat" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableSaturatedFat(v *float64) *ProductUpdate {
	if v != nil {
		_u.SetSaturatedFat(*v)
	}
	return _u
}

// AddSaturatedFat adds value to the "saturated_fat" field.
func (_u *ProductUpdate) AddSaturatedFat(v float64) *ProductUpdate {
	_u.mutation.AddSaturatedFat(v)
	return _u
}

// SetCarbohydrates sets the "carbohydrates" field.
func (_u *ProductUpdate) SetCarbohydrates(v float64) *ProductUpdate {
	_u.mutation.ResetCarbohydrates()
	_u.mutation.SetCarbohydrates(v)
	return _u
}

// SetNillableCarbohydrates sets the "carbohydrates" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableCarbohydrates(v *float64) *ProductUpdate {
	if v != nil {
		_u.SetCarbohydrates(*v)
	}
	return _u
}

// AddCarbohydrates adds value to the "carbohydrates" field.
func (_u *ProductUpdate) AddCarbohydrates(v float64) *ProductUpdate {
	_u.mutation.AddCarbohydrates(v)
	return _u
}

// SetFiber sets the "fiber" field.
func (_u *ProductUpdate) SetFiber(v float64) *ProductUpdate {
	_u.mutation.ResetFiber()
	_u.mutation.SetFiber(v)
	return _u
}

// SetNillableFiber sets the "fiber" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableFiber(v *float64) *ProductUpdate {
	if v != nil {
		_u.SetFiber(*v)
	}
	return _u
}

// AddFiber adds value to the "fiber" field.
func (_u *ProductUpdate) AddFiber(v float64) *ProductUpdate {
	_u.mutation.AddFiber(v)
	return _u
}

// SetSugars sets the "sugars" field.
func (_u *ProductUpdate) SetSugars(v float64) *ProductUpdate {
	_u.mutation.ResetSugars()
	_u.mutation.SetSugars(v)
	return _u
}

// SetNillableSugars sets the "sugars" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableSugars(v *float64) *ProductUpdate {
	if v != nil {
		_u.SetSugars(*v)
	}
	return _u
}

// AddSugars adds value to the "sugars" field.
func (_u *ProductUpdate) AddSugars(v float64) *ProductUpdate {
	_u.mutation.AddSugars(v)
	return _u
}

// SetSodium sets the "sodium" field.
func (_u *ProductUpdate) SetSodium(v float64) *ProductUpdate {
	_u.mutation.ResetSodium()
	_u.mutation.SetSodium(v)
	return _u
}

// SetNillableSodium sets the "sodium" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableSodium(v *float64) *ProductUpdate {
	if v != nil {
		_u.SetSodium(*v)
	}
	return _u
}

// AddSodium adds value to the "sodium" field.
func (_u *ProductUpdate) AddSodium(v float64) *ProductUpdate {
	_u.mutation.AddSodium(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProductUpdate) SetCreatedBy(v string) *ProductUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableCreatedBy(v *string) *ProductUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProductUpdate) ClearCreatedBy() *ProductUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Mutation returns the ProductMutation object of the builder.
func (_u *ProductUpdate) Mutation() *ProductMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := product.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Product.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Calories(); ok {
		if err := product.CaloriesValidator(v); err != nil {
			return &ValidationError{Name: "calories", err: fmt.Errorf(`ent: validator failed for field "Product.calories": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protein(); ok {
		if err := product.ProteinValidator(v); err != nil {
			return &ValidationError{Name: "protein", err: fmt.Errorf(`ent: validator failed for field "Product.protein": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Fat(); ok {
		if err := product.FatValidator(v); err != nil {
			return &ValidationError{Name: "fat", err: fmt.Errorf(`ent: validator failed for field "Product.fat": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SaturatedFat(); ok {
		if err := product.SaturatedFatValidator(v); err != nil {
			return &ValidationError{Name: "saturated_fat", err: fmt.Errorf(`ent: validator failed for field "Product.saturated_fat": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Carbohydrates(); ok {
		if err := product.CarbohydratesValidator(v); err != nil {
			return &ValidationError{Name: "carbohydrates", err: fmt.Errorf(`ent: validator failed for field "Product.carbohydrates": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Fiber(); ok {
		if err := product.FiberValidator(v); err != nil {
			return &ValidationError{Name: "fiber", err: fmt.Errorf(`ent: validator failed for field "Product.fiber": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sugars(); ok {
		if err := product.SugarsValidator(v); err != nil {
			return &ValidationError{Name: "sugars", err: fmt.Errorf(`ent: validator failed for field "Product.sugars": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sodium(); ok {
		if err := product.SodiumValidator(v); err != nil {
			return &ValidationError{Name: "sodium", err: fmt.Errorf(`ent: validator failed for field "Product.sodium": %w`, err)}
		}
	}
	return nil
}

func (_u *ProductUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Barcode(); ok {
		_spec.SetField(product.FieldBarcode, field.TypeString, value)
	}
	if _u.mutation.BarcodeCleared() {
		_spec.ClearField(product.FieldBarcode, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Brand(); ok {
		_spec.SetField(product.FieldBrand, field.TypeString, value)
	}
	if _u.mutation.BrandCleared() {
		_spec.ClearField(product.FieldBrand, field.TypeString)
	}
	if value, ok := _u.mutation.Calories(); ok {
		_spec.SetField(product.FieldCalories, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCalories(); ok {
		_spec.AddField(product.FieldCalories, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Protein(); ok {
		_spec.SetField(product.FieldProtein, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProtein(); ok {
		_spec.AddField(product.FieldProtein, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Fat(); ok {
		_spec.SetField(product.FieldFat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFat(); ok {
		_spec.AddField(product.FieldFat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SaturatedFat(); ok {
		_spec.SetField(product.FieldSaturatedFat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSaturatedFat(); ok {
		_spec.AddField(product.FieldSaturatedFat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Carbohydrates(); ok {
		_spec.SetField(product.FieldCarbohydrates, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCarbohydrates(); ok {
		_spec.AddField(product.FieldCarbohydrates, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Fiber(); ok {
		_spec.SetField(product.FieldFiber, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFiber(); ok {
		_spec.AddField(product.FieldFiber, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Sugars(); ok {
		_spec.SetField(product.FieldSugars, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSugars(); ok {
		_spec.AddField(product.FieldSugars, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Sodium(); ok {
		_spec.SetField(product.FieldSodium, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSodium(); ok {
		_spec.AddField(product.FieldSodium, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(product.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(product.FieldCreatedBy, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductMutation
}

// SetBarcode sets the "barcode" field.
func (_u *ProductUpdateOne) SetBarcode(v string) *ProductUpdateOne {
	_u.mutation.SetBarcode(v)
	return _u
}

// SetNillableBarcode sets the "barcode" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableBarcode(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetBarcode(*v)
	}
	return _u
}

// ClearBarcode clears the value of the "barcode" field.
func (_u *ProductUpdateOne) ClearBarcode() *ProductUpdateOne {
	_u.mutation.ClearBarcode()
	return _u
}

// SetName sets the "name" field.
func (_u *ProductUpdateOne) SetName(v string) *ProductUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableName(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBrand sets the "brand" field.
func (_u *ProductUpdateOne) SetBrand(v string) *ProductUpdateOne {
	_u.mutation.SetBrand(v)
	return _u
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableBrand(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetBrand(*v)
	}
	return _u
}

// ClearBrand clears the value of the "brand" field.
func (_u *ProductUpdateOne) ClearBrand() *ProductUpdateOne {
	_u.mutation.ClearBrand()
	return _u
}

// SetCalories sets the "calories" field.
func (_u *ProductUpdateOne) SetCalories(v float64) *ProductUpdateOne {
	_u.mutation.ResetCalories()
	_u.mutation.SetCalories(v)
	return _u
}

// SetNillableCalories sets the "calories" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableCalories(v *float64) *ProductUpdateOne {
	if v != nil {
		_u.SetCalories(*v)
	}
	return _u
}

// AddCalories adds value to the "calories" field.
func (_u *ProductUpdateOne) AddCalories(v float64) *ProductUpdateOne {
	_u.mutation.AddCalories(v)
	return _u
}

// SetProtein sets the "protein" field.
func (_u *ProductUpdateOne) SetProtein(v float64) *ProductUpdateOne {
	_u.mutation.ResetProtein()
	_u.mutation.SetProtein(v)
	return _u
}

// SetNillableProtein sets the "protein" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableProtein(v *float64) *ProductUpdateOne {
	if v != nil {
		_u.SetProtein(*v)
	}
	return _u
}

// AddProtein adds value to the "protein" field.
func (_u *ProductUpdateOne) AddProtein(v float64) *ProductUpdateOne {
	_u.mutation.AddProtein(v)
	return _u
}

// SetFat sets the "fat" field.
func (_u *ProductUpdateOne) SetFat(v float64) *ProductUpdateOne {
	_u.mutation.ResetFat()
	_u.mutation.SetFat(v)
	return _u
}

// SetNillableFat sets the "fat" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableFat(v *float64) *ProductUpdateOne {
	if v != nil {
		_u.SetFat(*v)
	}
	return _u
}

// AddFat adds value to the "fat" field.
func (_u *ProductUpdateOne) AddFat(v float64) *ProductUpdateOne {
	_u.mutation.AddFat(v)
	return _u
}

// SetSaturatedFat sets the "saturated_fat" field.
func (_u *ProductUpdateOne) SetSaturatedFat(v float64) *ProductUpdateOne {
	_u.mutation.ResetSaturatedFat()
	_u.mutation.SetSaturatedFat(v)
	return _u
}

// SetNillableSaturatedFat sets the "saturated_fat" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableSaturatedFat(v *float64) *ProductUpdateOne {
	if v != nil {
		_u.SetSaturatedFat(*v)
	}
	return _u
}

// AddSaturatedFat adds value to the "saturated_fat" field.
func (_u *ProductUpdateOne) AddSaturatedFat(v float64) *ProductUpdateOne {
	_u.mutation.AddSaturatedFat(v)
	return _u
}

// SetCarbohydrates sets the "carbohydrates" field.
func (_u *ProductUpdateOne) SetCarbohydrates(v float64) *ProductUpdateOne {
	_u.mutation.ResetCarbohydrates()
	_u.mutation.SetCarbohydrates(v)
	return _u
}

// SetNillableCarbohydrates sets the "carbohydrates" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableCarbohydrates(v *float64) *ProductUpdateOne {
	if v != nil {
		_u.SetCarbohydrates(*v)
	}
	return _u
}

// AddCarbohydrates adds value to the "carbohydrates" field.
func (_u *ProductUpdateOne) AddCarbohydrates(v float64) *ProductUpdateOne {
	_u.mutation.AddCarbohydrates(v)
	return _u
}

// SetFiber sets the "fiber" field.
func (_u *ProductUpdateOne) SetFiber(v float64) *ProductUpdateOne {
	_u.mutation.ResetFiber()
	_u.mutation.SetFiber(v)
	return _u
}

// SetNillableFiber sets the "fiber" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableFiber(v *float64) *ProductUpdateOne {
	if v != nil {
		_u.SetFiber(*v)
	}
	return _u
}

// AddFiber adds value to the "fiber" field.
func (_u *ProductUpdateOne) AddFiber(v float64) *ProductUpdateOne {
	_u.mutation.AddFiber(v)
	return _u
}

// SetSugars sets the "sugars" field.
func (_u *ProductUpdateOne) SetSugars(v float64) *ProductUpdateOne {
	_u.mutation.ResetSugars()
	_u.mutation.SetSugars(v)
	return _u
}

// SetNillableSugars sets the "sugars" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableSugars(v *float64) *ProductUpdateOne {
	if v != nil {
		_u.SetSugars(*v)
	}
	return _u
}

// AddSugars adds value to the "sugars" field.
func (_u *ProductUpdateOne) AddSugars(v float64) *ProductUpdateOne {
	_u.mutation.AddSugars(v)
	return _u
}

// SetSodium sets the "sodium" field.
func (_u *ProductUpdateOne) SetSodium(v float64) *ProductUpdateOne {
	_u.mutation.ResetSodium()
	_u.mutation.SetSodium(v)
	return _u
}

// SetNillableSodium sets the "sodium" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableSodium(v *float64) *ProductUpdateOne {
	if v != nil {
		_u.SetSodium(*v)
	}
	return _u
}

// AddSodium adds value to the "sodium" field.
func (_u *ProductUpdateOne) AddSodium(v float64) *ProductUpdateOne {
	_u.mutation.AddSodium(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProductUpdateOne) SetCreatedBy(v string) *ProductUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableCreatedBy(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProductUpdateOne) ClearCreatedBy() *ProductUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Mutation returns the ProductMutation object of the builder.
func (_u *ProductUpdateOne) Mutation() *ProductMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (_u *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Product entity.
func (_u *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := product.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Product.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Calories(); ok {
		if err := product.CaloriesValidator(v); err != nil {
			return &ValidationError{Name: "calories", err: fmt.Errorf(`ent: validator failed for field "Product.calories": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protein(); ok {
		if err := product.ProteinValidator(v); err != nil {
			return &ValidationError{Name: "protein", err: fmt.Errorf(`ent: validator failed for field "Product.protein": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Fat(); ok {
		if err := product.FatValidator(v); err != nil {
			return &ValidationError{Name: "fat", err: fmt.Errorf(`ent: validator failed for field "Product.fat": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SaturatedFat(); ok {
		if err := product.SaturatedFatValidator(v); err != nil {
			return &ValidationError{Name: "saturated_fat", err: fmt.Errorf(`ent: validator failed for field "Product.saturated_fat": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Carbohydrates(); ok {
		if err := product.CarbohydratesValidator(v); err != nil {
			return &ValidationError{Name: "carbohydrates", err: fmt.Errorf(`ent: validator failed for field "Product.carbohydrates": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Fiber(); ok {
		if err := product.FiberValidator(v); err != nil {
			return &ValidationError{Name: "fiber", err: fmt.Errorf(`ent: validator failed for field "Product.fiber": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sugars(); ok {
		if err := product.SugarsValidator(v); err != nil {
			return &ValidationError{Name: "sugars", err: fmt.Errorf(`ent: validator failed for field "Product.sugars": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sodium(); ok {
		if err := product.SodiumValidator(v); err != nil {
			return &ValidationError{Name: "sodium", err: fmt.Errorf(`ent: validator failed for field "Product.sodium": %w`, err)}
		}
	}
	return nil
}

func (_u *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Barcode(); ok {
		_spec.SetField(product.FieldBarcode, field.TypeString, value)
	}
	if _u.mutation.BarcodeCleared() {
		_spec.ClearField(product.FieldBarcode, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Brand(); ok {
		_spec.SetField(product.FieldBrand, field.TypeString, value)
	}
	if _u.mutation.BrandCleared() {
		_spec.ClearField(product.FieldBrand, field.TypeString)
	}
	if value, ok := _u.mutation.Calories(); ok {
		_spec.SetField(product.FieldCalories, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCalories(); ok {
		_spec.AddField(product.FieldCalories, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Protein(); ok {
		_spec.SetField(product.FieldProtein, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProtein(); ok {
		_spec.AddField(product.FieldProtein, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Fat(); ok {
		_spec.SetField(product.FieldFat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFat(); ok {
		_spec.AddField(product.FieldFat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SaturatedFat(); ok {
		_spec.SetField(product.FieldSaturatedFat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSaturatedFat(); ok {
		_spec.AddField(product.FieldSaturatedFat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Carbohydrates(); ok {
		_spec.SetField(product.FieldCarbohydrates, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCarbohydrates(); ok {
		_spec.AddField(product.FieldCarbohydrates, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Fiber(); ok {
		_spec.SetField(product.FieldFiber, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFiber(); ok {
		_spec.AddField(product.FieldFiber, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Sugars(); ok {
		_spec.SetField(product.FieldSugars, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSugars(); ok {
		_spec.AddField(product.FieldSugars, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Sodium(); ok {
		_spec.SetField(product.FieldSodium, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSodium(); ok {
		_spec.AddField(product.FieldSodium, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(product.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(product.FieldCreatedBy, field.TypeString)
	}
	_node = &Product{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
