// Code generated by ent, DO NOT EDIT.

package ent

import (
	"devarminas/kcal-track-api/ent/product"
	"devarminas/kcal-track-api/ent/schema"
	"devarminas/kcal-track-api/ent/userlog"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[2].Descriptor()
	// product.NameValidator is a validator for the "name" field. It is called by the builders before save.
	product.NameValidator = productDescName.Validators[0].(func(string) error)
	// productDescCalories is the schema descriptor for calories field.
	productDescCalories := productFields[4].Descriptor()
	// product.CaloriesValidator is a validator for the "calories" field. It is called by the builders before save.
	product.CaloriesValidator = productDescCalories.Validators[0].(func(float64) error)
	// productDescProtein is the schema descriptor for protein field.
	productDescProtein := productFields[5].Descriptor()
	// product.ProteinValidator is a validator for the "protein" field. It is called by the builders before save.
	product.ProteinValidator = productDescProtein.Validators[0].(func(float64) error)
	// productDescFat is the schema descriptor for fat field.
	productDescFat := productFields[6].Descriptor()
	// product.FatValidator is a validator for the "fat" field. It is called by the builders before save.
	product.FatValidator = productDescFat.Validators[0].(func(float64) error)
	// productDescSaturatedFat is the schema descriptor for saturated_fat field.
	productDescSaturatedFat := productFields[7].Descriptor()
	// product.SaturatedFatValidator is a validator for the "saturated_fat" field. It is called by the builders before save.
	product.SaturatedFatValidator = productDescSaturatedFat.Validators[0].(func(float64) error)
	// productDescCarbohydrates is the schema descriptor for carbohydrates field.
	productDescCarbohydrates := productFields[8].Descriptor()
	// product.CarbohydratesValidator is a validator for the "carbohydrates" field. It is called by the builders before save.
	product.CarbohydratesValidator = productDescCarbohydrates.Validators[0].(func(float64) error)
	// productDescFiber is the schema descriptor for fiber field.
	productDescFiber := productFields[9].Descriptor()
	// product.FiberValidator is a validator for the "fiber" field. It is called by the builders before save.
	product.FiberValidator = productDescFiber.Validators[0].(func(float64) error)
	// productDescSugars is the schema descriptor for sugars field.
	productDescSugars := productFields[10].Descriptor()
	// product.SugarsValidator is a validator for the "sugars" field. It is called by the builders before save.
	product.SugarsValidator = productDescSugars.Validators[0].(func(float64) error)
	// productDescSodium is the schema descriptor for sodium field.
	productDescSodium := productFields[11].Descriptor()
	// product.SodiumValidator is a validator for the "sodium" field. It is called by the builders before save.
	product.SodiumValidator = productDescSodium.Validators[0].(func(float64) error)
	// productDescID is the schema descriptor for id field.
	productDescID := productFields[0].Descriptor()
	// product.DefaultID holds the default value on creation for the id field.
	product.DefaultID = productDescID.Default.(func() uuid.UUID)
	userlogFields := schema.UserLog{}.Fields()
	_ = userlogFields
	// userlogDescAmount is the schema descriptor for amount field.
	userlogDescAmount := userlogFields[1].Descriptor()
	// userlog.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	userlog.AmountValidator = userlogDescAmount.Validators[0].(func(float64) error)
	// userlogDescDate is the schema descriptor for date field.
	userlogDescDate := userlogFields[2].Descriptor()
	// userlog.DefaultDate holds the default value on creation for the date field.
	userlog.DefaultDate = userlogDescDate.Default.(func() time.Time)
	// userlogDescID is the schema descriptor for id field.
	userlogDescID := userlogFields[0].Descriptor()
	// userlog.DefaultID holds the default value on creation for the id field.
	userlog.DefaultID = userlogDescID.Default.(func() uuid.UUID)
}
