// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"devarminas/kcal-track-api/ent/predicate"
	"devarminas/kcal-track-api/ent/product"
	"devarminas/kcal-track-api/ent/userlog"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserLogUpdate is the builder for updating UserLog entities.
type UserLogUpdate struct {
	config
	hooks    []Hook
	mutation *UserLogMutation
}

// Where appends a list predicates to the UserLogUpdate builder.
func (_u *UserLogUpdate) Where(ps ...predicate.UserLog) *UserLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserLogUpdate) SetAmount(v float64) *UserLogUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserLogUpdate) SetNillableAmount(v *float64) *UserLogUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserLogUpdate) AddAmount(v float64) *UserLogUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetDate sets the "date" field.
func (_u *UserLogUpdate) SetDate(v time.Time) *UserLogUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *UserLogUpdate) SetNillableDate(v *time.Time) *UserLogUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserLogUpdate) SetUserID(v string) *UserLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserLogUpdate) SetNillableUserID(v *string) *UserLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *UserLogUpdate) ClearUserID() *UserLogUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *UserLogUpdate) SetProductID(v uuid.UUID) *UserLogUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *UserLogUpdate) SetNillableProductID(v *uuid.UUID) *UserLogUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *UserLogUpdate) SetProduct(v *Product) *UserLogUpdate {
	return _u.SetProductID(v.ID)
}

// Mutation returns the UserLogMutation object of the builder.
func (_u *UserLogUpdate) Mutation() *UserLogMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *UserLogUpdate) ClearProduct() *UserLogUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserLogUpdate) check() error {
	if v, ok := _u.mutation.Amount(); ok {
		if err := userlog.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "UserLog.amount": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserLog.product"`)
	}
	return nil
}

func (_u *UserLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userlog.Table, userlog.Columns, sqlgraph.NewFieldSpec(userlog.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(userlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(userlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(userlog.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userlog.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(userlog.FieldUserID, field.TypeString)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userlog.ProductTable,
			Columns: []string{userlog.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userlog.ProductTable,
			Columns: []string{userlog.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserLogUpdateOne is the builder for updating a single UserLog entity.
type UserLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserLogMutation
}

// SetAmount sets the "amount" field.
func (_u *UserLogUpdateOne) SetAmount(v float64) *UserLogUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserLogUpdateOne) SetNillableAmount(v *float64) *UserLogUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserLogUpdateOne) AddAmount(v float64) *UserLogUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetDate sets the "date" field.
func (_u *UserLogUpdateOne) SetDate(v time.Time) *UserLogUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *UserLogUpdateOne) SetNillableDate(v *time.Time) *UserLogUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserLogUpdateOne) SetUserID(v string) *UserLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserLogUpdateOne) SetNillableUserID(v *string) *UserLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *UserLogUpdateOne) ClearUserID() *UserLogUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *UserLogUpdateOne) SetProductID(v uuid.UUID) *UserLogUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *UserLogUpdateOne) SetNillableProductID(v *uuid.UUID) *UserLogUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *UserLogUpdateOne) SetProduct(v *Product) *UserLogUpdateOne {
	return _u.SetProductID(v.ID)
}

// Mutation returns the UserLogMutation object of the builder.
func (_u *UserLogUpdateOne) Mutation() *UserLogMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *UserLogUpdateOne) ClearProduct() *UserLogUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// Where appends a list predicates to the UserLogUpdate builder.
func (_u *UserLogUpdateOne) Where(ps ...predicate.UserLog) *UserLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserLogUpdateOne) Select(field string, fields ...string) *UserLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserLog entity.
func (_u *UserLogUpdateOne) Save(ctx context.Context) (*UserLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserLogUpdateOne) SaveX(ctx context.Context) *UserLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserLogUpdateOne) check() error {
	if v, ok := _u.mutation.Amount(); ok {
		if err := userlog.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "UserLog.amount": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserLog.product"`)
	}
	return nil
}

func (_u *UserLogUpdateOne) sqlSave(ctx context.Context) (_node *UserLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userlog.Table, userlog.Columns, sqlgraph.NewFieldSpec(userlog.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userlog.FieldID)
		for _, f := range fields {
			if !userlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(userlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(userlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(userlog.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userlog.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(userlog.FieldUserID, field.TypeString)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userlog.ProductTable,
			Columns: []string{userlog.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userlog.ProductTable,
			Columns: []string{userlog.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
