// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"devarminas/kcal-track-api/ent/product"
	"devarminas/kcal-track-api/ent/userlog"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserLogCreate is the builder for creating a UserLog entity.
type UserLogCreate struct {
	config
	mutation *UserLogMutation
	hooks    []Hook
}

// SetAmount sets the "amount" field.
func (_c *UserLogCreate) SetAmount(v float64) *UserLogCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetDate sets the "date" field.
func (_c *UserLogCreate) SetDate(v time.Time) *UserLogCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_c *UserLogCreate) SetNillableDate(v *time.Time) *UserLogCreate {
	if v != nil {
		_c.SetDate(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserLogCreate) SetUserID(v string) *UserLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *UserLogCreate) SetNillableUserID(v *string) *UserLogCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *UserLogCreate) SetProductID(v uuid.UUID) *UserLogCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UserLogCreate) SetID(v uuid.UUID) *UserLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserLogCreate) SetNillableID(v *uuid.UUID) *UserLogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProduct sets the "product" edge to the Product entity.
func (_c *UserLogCreate) SetProduct(v *Product) *UserLogCreate {
	return _c.SetProductID(v.ID)
}

// Mutation returns the UserLogMutation object of the builder.
func (_c *UserLogCreate) Mutation() *UserLogMutation {
	return _c.mutation
}

// Save creates the UserLog in the database.
func (_c *UserLogCreate) Save(ctx context.Context) (*UserLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserLogCreate) SaveX(ctx context.Context) *UserLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserLogCreate) defaults() {
	if _, ok := _c.mutation.Date(); !ok {
		v := userlog.DefaultDate()
		_c.mutation.SetDate(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := userlog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserLogCreate) check() error {
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "UserLog.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := userlog.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "UserLog.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "UserLog.date"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "UserLog.product_id"`)}
	}
	if len(_c.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "UserLog.product"`)}
	}
	return nil
}

func (_c *UserLogCreate) sqlSave(ctx context.Context) (*UserLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserLogCreate) createSpec() (*UserLog, *sqlgraph.CreateSpec) {
	var (
		_node = &UserLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userlog.Table, sqlgraph.NewFieldSpec(userlog.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(userlog.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(userlog.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userlog.FieldUserID, field.TypeString, value)
		_node.UserID = &value
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userlog.ProductTable,
			Columns: []string{userlog.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserLogCreateBulk is the builder for creating many UserLog entities in bulk.
type UserLogCreateBulk struct {
	config
	err      error
	builders []*UserLogCreate
}

// Save creates the UserLog entities in the database.
func (_c *UserLogCreateBulk) Save(ctx context.Context) ([]*UserLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserLogCreateBulk) SaveX(ctx context.Context) []*UserLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
